<?
/**
 * Pagebreak Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */

?>

<nav>
    <ol class="table-of-contents">
        <li>
            <a href="#">Introduction</a>
        </li>
        <li>
            <a href="#">Point 1</a>
        </li>
        <li>
            <a href="#">Point 2</a>
        </li>
        <li>
            <a href="#">Point 3</a>
        </li>
        <li>
            <a href="#">Conclusion</a>
        </li>
    </ol>
</nav>
