<?
/**
 * Grid Page View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<a id="top"></a>
<include Navbar/>
<div id="wrapper" class="row">
    <div class="large-12 columns">
        <include Form_begin/>
        <include Header/>
        <div id="wrapper" class="row">
            <section class="grid row">
                <include Grid role=main/>
                    <include Pagination wrap=nav wrap_class=pagination/>
            </section>
        </div>
        <include Form_end/>
    </div>
</div>
<include Footer/>
