<?
/**
 * @package    Molajo
 * @copyright  2013 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div id="main" class="large-9 push-3 columns">
    <include article wrap=article role=main/>
        <? if ((int)$runtime_data->resource->data->parameters->enable_response_comments == 1) { ?>
        <include Author wrap=aside wrap_class=author-profile/>
            <section>
                <include Comment/>
                <include Comments/>
                <include Commentform/>
            </section>
            <? } ?>
</div>
<div class="large-3 pull-9 columns">
    <ul class="side-nav">
        <li><a href="#">Section 1</a></li>
        <li><a href="#">Section 2</a></li>
        <li><a href="#">Section 3</a></li>
        <li><a href="#">Section 4</a></li>
        <li><a href="#">Section 5</a></li>
        <li><a href="#">Section 6</a></li>
    </ul>
    <p><img src="http://placehold.it/320x240&text=Ad"/></p>
</div>



