<?
/**
 * List Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */


if (isset($this->row->title)) {
    $title = $this->row->title;
} else {
    $title = $this->row->full_name;
}
?>
<li>
    <? if (isset($this->row->catalog_id_url)) { ?>
    <a href="<? echo $this->row->catalog_id_url; ?>">
        <? } ?>
        <? echo $title ?>
        <? if (isset($this->row->catalog_id_url)) { ?>
    </a>
<? } ?>
</li>
