<?
/**
 * Form Columns 1 Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
$list = '';

if (isset($this->row->locked) && (int) $this->row->locked === 1  && trim($this->row->value) === '') :
    $this->row->type    = 'string';
    $model_name         = ' model_name=' . trim(strtolower($this->row->form_field_name));
elseif (isset($this->row->datalist) && $this->row->datalist <> '') :
    $list               = 'datalist_' . trim(strtolower($this->row->datalist))  . '_' .  trim(strtolower($this->row->name));
else :
    $model_name         = ' model_name=' . trim(strtolower($this->row->form_field_name));
endif;

?>
<div class="row">
    <div class="small-12 columns">
        <? if ($list === '') : ?>
            {I template=Form_<?= $this->row->type; ?> model_type=plugin_data<?= $model_name; ?> I}
        <? else : ?>
            {I template=Form_selectlist model_name=<?= trim($list); ?> I}
        <? endif; ?>
    </div>
</div>
