<?
/**
 * Forminput Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */

$tooltip_css_class = 'has-tip';
if ($this->row->type == 'hidden') {
} else {
    ?>
    <span class="<? echo $tooltip_css_class; ?>" title="<? echo $this->row->tooltip; ?>">
<label for="<? echo $this->row->id; ?>"><? echo $this->row->label; ?></label></span>
<? } ?>
<input
