<?
/**
 * List Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */

if (isset($this->row->title)) :
    $title = $this->row->title;
else :
    $title = $this->row->full_name;
endif;
?>
<li>
    <? if (isset($this->row->catalog_id_url)) : ?>
    <a href="<?= $this->row->catalog_id_url; ?>">
        <? endif; ?>
        <?= $title ?>
        <? if (isset($this->row->catalog_id_url)) : ?>
    </a>
<? endif; ?>
</li>
