<?
/**
 * @package    Molajo
 * @copyright  2013 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="twelve columns">
        <h1>Not found <span>:(</span></h1>

        <p>Sorry, but the page you were trying to view does not exist.</p>

        <p>It looks like this was the result of either:</p>
        <ul>
            <li>a mistyped address</li>
            <li>an out-of-date link</li>
        </ul>

        <h3>Would you like to try our site search?</h3>

        <div class="row">
            <div class="five columns">
                <div class="row collapse">
                    <div class="eight mobile-three columns">
                        <input type="text"/>
                    </div>
                    <div class="four mobile-one columns">
                        <a href="#" class="postfix button expand">Search</a>
                    </div>
                </div>
            </div>
        </div>

        <p>Feel free to <a href="pages/contact-us">contact us</a> if you believe this to be an error.</p>

    </div>
</div>
