<?
/**
 * Default Wrap View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */

if ((int)$this->runtime_data->application->parameters->application_html5 == 1
    && ($this->plugin_data->render->extension->title == 'Article'
        || $this->plugin_data->render->extension->title == 'Aside'
        || $this->plugin_data->render->extension->title == 'Footer'
        || $this->plugin_data->render->extension->title == 'Header'
        || $this->plugin_data->render->extension->title == 'Hgroup'
        || $this->plugin_data->render->extension->title == 'Nav'
        || $this->plugin_data->render->extension->title == 'Section')
):
    $headerType = $this->plugin_data->render->extension->title; else :
    $headerType = 'div';
endif;
$headerType = strtolower($headerType);
?>
</<? echo $headerType; ?>>
