<?
/**
 * Default Wrap View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */

if ((int)$this->runtime_data->application->parameters->application_html5 == 1
    && ($this->plugin_data->render->extension->title == 'Article'
        || $this->plugin_data->render->extension->title == 'Aside'
        || $this->plugin_data->render->extension->title == 'Footer'
        || $this->plugin_data->render->extension->title == 'Header'
        || $this->plugin_data->render->extension->title == 'Hgroup'
        || $this->plugin_data->render->extension->title == 'Nav'
        || $this->plugin_data->render->extension->title == 'Section')
):
    $headerType = $this->plugin_data->render->extension->title; else :
    $headerType = 'div';
endif;
$headerType = strtolower($headerType);

$headerId = trim($this->plugin_data->render->extension->parameters->wrap_view_css_id);
if ($headerId == '') :
else :
    $headerId = ' id="' . $headerId . '"';
endif;

$headerclass = trim($this->plugin_data->render->extension->parameters->wrap_view_css_class);
if ($headerclass == '') :
else :
    $headerclass = ' class="' . $headerclass . '"';
endif;

$headerRole = trim($this->plugin_data->render->extension->parameters->wrap_view_role);
if ($headerRole == '') :
else :
    $headerRole = ' role="' . $headerRole . '"';
endif;

$headerProperty = trim($this->plugin_data->render->extension->parameters->wrap_view_property);
if ($headerProperty == '') :
else :
    $headerProperty = ' property="' . $headerProperty . '"';
endif;
?>
    <<? echo trim($headerType . $headerId . $headerclass . $headerRole . $headerProperty); ?>>
<?
$headingLevel = $this->plugin_data->render->extension->parameters->wrap_view_header_level;
if ((int)$this->runtime_data->application->parameters->application_html5 == 1):
    if ($this->plugin_data->render->extension->parameters->wrap_view_show_title === true
        && $this->plugin_data->render->extension->parameters->wrap_view_show_subtitle === true
    ) : ?>
        <hgroup>
    <? endif;
endif;

if ($this->plugin_data->render->extension->parameters->wrap_view_show_title === true) :  ?>
    <h<? echo $headingLevel; ?>>
        <? echo $this->row->title; ?>
    </h<? echo $headingLevel ++; ?>>
<?
endif;

if ($this->plugin_data->render->extension->parameters->wrap_view_show_subtitle === true) :  ?>
    <h<? echo $headingLevel; ?>>
        <? echo $this->row->subtitle; ?>
    </h<? echo $headingLevel ++; ?>>
<?
endif;

if ((int)$this->runtime_data->application->parameters->application_html5 == 1) :
    if ($this->plugin_data->render->extension->parameters->wrap_view_show_title === true
        && $this->plugin_data->render->extension->parameters->wrap_view_show_subtitle === true
    ) : ?>
        </hgroup>
    <? endif;
endif;
