<?

/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */

?>
<div class="row">
    <div class="twelve columns">
        <? echo $this->row->content_text; ?>
    </div>
</div>
<div class="row">
    <div class="twelve columns">
        <include Author wrap=Section value=author/>
    </div>
</div>
