<?

/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="eleven columns">
        <h2><? echo $this->row->title; ?></h2>
    </div>
    <div class="one columns">
        <form action="<? echo $this->row->catalog_id_url ?>/edit">
            <input type="submit" class="submit button small" value="Edit">
        </form>
    </div>
</div>
