<?
/**
 * Configuration View Template
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
$type  = 'Form Defaults';
$theme = 'datalist_themes_form';
$page  = 'datalist_pageviews_form';
include __DIR__ . '/Include.phtml';

$type  = 'Item Defaults';
$theme = 'datalist_themes_item';
$page  = 'datalist_pageviews_item';
include __DIR__ . '/Include.phtml';

$type  = 'List Defaults';
$theme = 'datalist_themes_list';
$page  = 'datalist_pageviews_list';
include __DIR__ . '/Include.phtml';
