<?
/**
 * Metadata Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

$application_html5 = $this->row->application_html5;
$end = $this->row->end;
if (trim($this->row->content) == '') {
} elseif ($this->row->name == 'mimetype' && (int)$this->row->application_html5 === 1) {
} else {
    ?>
    <meta <? echo $this->row->label; ?>="<? echo $this->row->name; ?>" content="<? echo $this->row->content; ?>"<? echo $end;
}
