<?
/**
 * Gallery Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<div class="portlet-header panel">
    <h4>Gallery</h4>
</div>
<div class="portlet-content panel">
    <ul class="inline-list">
        <li><a href="#"><img src="http://placehold.it/100x100/000000/ffffff&text=1"/></a></li>
        <li><a href="#"><img src="http://placehold.it/100x100/000099/ffffff&text=2"/></a></li>
        <li><a href="#"><img src="http://placehold.it/100x100/660099/ffffff&text=3"/></a></li>
        <li><a href="#"><img src="http://placehold.it/100x100/CC0000/ffffff&text=4"/></a></li>
        <li><a href="#"><img src="http://placehold.it/100x100/CC0099/ffffff&text=5"/></a></li>
        <li><a href="#"><img src="http://placehold.it/100x100/99FFCC/000000&text=6"/></a></li>
        <li><a href="#"><img src="http://placehold.it/100x100/FFFF33/000000&text=7"/></a></li>
        <li><a href="#"><img src="http://placehold.it/100x100/6666CC/000000&text=8"/></a></li>
        <li><a href="#"><img src="http://placehold.it/100x100/ffffff/000000&text=9"/></a></li>
    </ul>
</div>
