<?

/**
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */

?>
<div class="row">
    <div class="twelve columns">
        <?= $this->row->content_text; ?>
    </div>
</div>
<div class="row">
    <div class="twelve columns">
        {I Author wrap=Section I}
    </div>
</div>
