Molajo has several README files located:

1. WORKING WITH MOLAJO LAYOUTS

    layouts/readme

    I. INTRODUCTION
    II. WHAT IS A MOLAJO LAYOUT?
    III. WHERE ARE LAYOUTS LOCATED?
    IV. HOW TO DETERMINE WHAT LAYOUT AN EXTENSION IS USING?
    V. HOW DO I CREATE, INSTALL, AND SHARE LAYOUTS?
    VI. HOW DO I OVERRIDE A LAYOUT?
    VII. WORKING WITH CSS AND JS FOR THE APPLICATION, COMPONENT, ASSET, AND/OR LAYOUT
    VIII. USING QUERY RESULTS IN LAYOUTS
    IX. WHAT DATA IS AVAILABLE WITHIN A LAYOUT FILE?
    X. WORKING WITH DATES
    XI. INTEGRATING OTHER EXTENSION OUTPUT WITHIN A LAYOUT
    XII. WORKING WITH IMAGES
    XIII. USING OTHER TEMPLATE SYSTEMS

2. WORKING WITH MOLAJO COMPONENTS

    administrator/component/your-component-name 


This README file on the root of the website lists all README files available.

