{
"application_name":"Integrated Data System",
"application_home_catalog_id":"139",
"application_logon_requirement":"0",

"log_user_update_activity":"1",
"log_user_view_activity":"1",
"log_catalog_update_activity":"1",
"log_catalog_view_activity":"1",

"url_sef":"1",
"url_sef_rewrite":"1",
"url_sef_suffix":"0",
"url_unicode_slugs":"0",
"url_force_ssl":"0",

"language":"en-GB",
"language_direction":"ltr",
"language_multilingual":"0",
"language_utc_offset":"UTC",

"debug":"1",
"debug_output":"Application,Authorisation,Queries,Rendering,Routing,Services,Triggers",
"debug_start_with":"Initialise",
"debug_end_with":"Response",
"debug_verbose":"0",
"debug_output_queries_table_registry":"0",
"debug_output_queries_sql":"1",
"debug_output_queries_query_results":"1",

"head_template_view_id":"23",
"head_wrap_view_id":"66",
"defer_template_view_id":"265",
"defer_wrap_view_id":"66",

"message_template_view_id":"44",
"message_wrap_view_id":"61",

"offline_theme_id":"99",
"offline_page_view_id":"57",
"offline":"0",
"offline_message":"This site is not available.<br/> Please check back again soon.",

"error_theme_id":"99",
"error_page_view_id":"56",
"error_404_message":"Page not found",
"error_403_message":"Not authorised",

"criteria_log_user_activity_create":"0",
"criteria_log_user_activity_read":"0",
"criteria_log_user_activity_update":"0",
"criteria_log_user_activity_delete":"0",
"criteria_enable_draft_save":"1",
"criteria_enable_version_history":"1",
"criteria_maximum_version_count":"5",
"criteria_enable_hit_counts":"1",
"criteria_enable_comments":"1",
"criteria_enable_ratings":"1",
"criteria_enable_notifications":"1",
"criteria_enable_tweets":"1",
"criteria_enable_ping":"1",
"criteria_snippet_length":"200",
"criteria_asset_priority_site":"100",
"criteria_asset_priority_application":"200",
"criteria_asset_priority_user":"300",
"criteria_asset_priority_extension":"400",
"criteria_asset_priority_request":"500",
"criteria_asset_priority_category":"600",
"criteria_asset_priority_menu_item":"700",
"criteria_asset_priority_source":"800",
"criteria_asset_priority_theme":"900",

"criteria_image_xsmall":"50",
"criteria_image_small":"75",
"criteria_image_medium":"150",
"criteria_image_large":"300",
"criteria_image_xlarge":"500",
"criteria_image_folder":"images",
"criteria_thumb_folder":"thumbs",

"gravatar":"1",
"gravatar_size":"50",
"gravatar_type":"monsterid",
"gravatar_rating":"pg",
"gravatar_image":"1",

"criteria_snippet_length":"200",

"item_theme_id":"98",
"item_page_view_id":"55",
"item_page_view_css_id":"",
"item_page_view_css_class":"",
"item_template_view_id":"21",
"item_template_view_css_id":"",
"item_template_view_css_class":"",
"item_wrap_view_id":"66",
"item_wrap_view_css_id":"",
"item_wrap_view_css_class":"",
"item_model_name":"Content",
"item_model_type":"Item",
"item_model_query_object":"Item",

"form_theme_id":"98",
"form_page_view_id":"55",
"form_page_view_css_id":"",
"form_page_view_css_class":"",
"form_template_view_id":"25",
"form_template_view_css_id":"",
"form_template_view_css_class":"",
"form_wrap_view_id":"66",
"form_wrap_view_css_id":"",
"form_wrap_view_css_class":"",
"form_model_name":"Content",
"form_model_type":"Item",
"form_model_query_object":"Edit",

"list_theme_id":"98",
"list_page_view_id":"55",
"list_page_view_css_id":"",
"list_page_view_css_class":"",
"list_template_view_id":"33",
"list_template_view_css_id":"",
"list_template_view_css_class":"",
"list_wrap_view_id":"",
"list_wrap_view_css_id":"",
"list_wrap_view_css_class":"",
"list_model_name":"Content",
"list_model_type":"List",
"list_model_query_object":"List",

"criteria_list_display_archived_content":"1",
"criteria_list_display_featured_content":"0",
"criteria_list_display_stickied_content":"0",
"criteria_list_display_published_date_begin":"0",
"criteria_list_display_published_date_end":"1",
"criteria_list_display_category_list":"0",
"criteria_list_display_tag_list":"0",
"criteria_list_display_author_list":"0",
"criteria_list_begin":"1",
"criteria_list_length":"0",
"criteria_list_order_by_field1":"start_publishing_datetime",
"criteria_list_order_by_direction1":"DESC",
"criteria_list_order_by_field2":"",
"criteria_list_order_by_direction2":"",
"criteria_list_order_by_field3":"",
"criteria_list_order_by_direction3":""
}
