<?
/**
 * Configuration Customfields Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
if ($this->row->name == 'none') :
else : ?>
    <div class="row <?= $this->row->even_or_odd; ?>">
        <div class="large-4 small-10 columns">
            <?= $this->row->name; ?>
        </div>
        <div class="large-2 columns show-for-large-up">
            <?= $this->row->type; ?>
        </div>
        <div class="large-2 columns show-for-large-up">
            <? if ((int)$this->row->null == 0) : ?>
                {T False T}
            <? else : ?>
                {T True T}
            <? endif; ?>
        </div>
        <div class="large-2 columns show-for-large-up">
            <?= $this->row->default;; ?>
        </div>
        <div class="large-2 small-2 columns">
        <span class="right">
            <a href="#" class="button tiny alert radius">{T Delete T}</a>
        </span>
        </div>
    </div>
<? endif;
