<?
/**
 * Messages Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<div class="<? echo $this->row->class; ?>">
    <? echo $this->row->message; ?>
    <a class="close" href="<? echo $this->row->action; ?>#">&times;</a>
    <h4 class="alert-heading"><? echo $this->row->heading; ?></h4>
</div>
