<?
/**
 * Gridpermissions Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
$action = $runtime_data->page->urls['page'];
if ($row->enable == 1) {
    ?>
    <div class="grid-permissions grid-batch">
        <ol class="grid-batch">
            <li><input type="submit" class="submit button small radius" name="submit" id="AssignPermissions"
                       value="Assign">
            </li>
            <li><strong><? echo $this->language_controller->translate('or'); ?></strong></li>
            <li><input type="submit" class="submit button small radius" name="submit" id="RemovePermissions"
                       value="Remove">
            </li>
            <li><input id="create" type="radio" value="create" name="permission"><label
                    for="create"><? echo $this->language_controller->translate('Create'); ?></label></li>
            <li><input id="read" type="radio" value="read" name="permission"><label
                    for="read"><? echo $this->language_controller->translate('Read'); ?></label></li>
            <li><input id="update" type="radio" value="update" name="permission"><label
                    for="update"><? echo $this->language_controller->translate('Update'); ?></label></li>
            <li><input id="publish" type="radio" value="publish" name="permission"><label
                    for="publish"><? echo $this->language_controller->translate('Publish'); ?></label></li>
            <li><input id="delete" type="radio" value="delete" name="permission"><label
                    for="delete"><? echo $this->language_controller->translate('Delete'); ?></label></li>
            <li>
                <include formselectlist datalist=groups/>
            </li>
            <li><strong><? echo $this->language_controller->translate('Permissions'); ?></strong></li>
        </ol>
    </div>
<?
}
