<?
/**
 * Admindashboard Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
{I template=Form_begin form_name=dashboard I}

<section class="dashboard">
    <div class="sortable">
        <br><br><br><br>

        <h1>This will be the very last thing. It will pull from the section content.</h1>
        <? //echo $this->registry->get('Plugindata', 'PortletOptions'); ?>
    </div>
</section>
