<?
/**
 * Pagination Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
if ($this->row->current === 0) {
    $class   = '';
    $link    = '<a href="' . $this->row->link . '">';
    $linkend = '</a>';
} else {
    $class   = 'class="unavailable"';
    $link    = '';
    $linkend = '';
}
?>
<li <? echo $class; ?>>
    <? echo $link; ?><? echo $this->row->link_text; ?><? echo $linkend; ?>
</li>
