<?
/**
 * Pagination Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */


if ($this->row->next_page === 0) {
    $class   = 'class="arrow unavailable"';
    $link    = '';
    $linkend = '';
} else {
    $class   = 'class="arrow"';
    $link    = '<a href="' . $this->row->next_link . '">';
    $linkend = '</a>';
}
?>
<li <? echo $class; ?>>
    <? echo $link; ?>&raquo;<? echo $linkend; ?>
</li>
</ul>
