<?
/**
 * Contentlist Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

?>
<p>
    <a href="<? echo $this->row->catalog_id_url; ?>"><strong><? echo $this->row->title; ?></strong></a>
    <? if ($this->runtime_data->display_snippet == 1) {
        echo '<br />' . $this->row->content_text_snippet;
    }
    if ($this->runtime_data->display_author_name == 1) {
        echo '<br />' . '<strong>' . $this->language_controller->translate(
                'Written by'
            ) . ':</strong> ' . $this->row->author_full_name;
    }
    if ($this->runtime_data->display_published_date == 1) {
        echo '<br />' . '<strong>' . $this->language_controller->translate(
                'Published'
            ) . ':</strong> ' . $this->row->start_publishing_datetime_pretty_date;
    } ?>
</p>
