<?
/**
 * Gridcheckin Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
$action = $this->runtime_data->page->urls['page'];
if ($this->row->enable == 1) {
    ?>
    <div class="grid-checkin grid-batch">
        <ol class="grid-batch">
            <li><strong><? echo $this->language_controller->translate('Checkin Content'); ?></strong></li>
            <li><input type="submit" class="submit button small radius" name="submit" id="Checkin" value="Checkin"/>
            </li>
        </ol>
    </div>
<?
}
