<?
/**
 * Form Numeric Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<span data-tooltip class="has-tip" title="{T <?= $this->row->name; ?> T}">
    <label for="<?= $this->row->name; ?>">
        {T <?= $this->row->name; ?> T}
    </label>
</span>
<input type="number" name="<?= $this->row->name; ?>" value="<?= $this->row->value; ?>" min="0" max="10" step="5"/>
