<?
/**
 * Configuration Grid Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
$list = '';
if ($this->row->type == 'datalist') {
    $list = 'datalist' . $this->row->listname;
}
?>
<? if ($this->row->even_or_odd == 'odd') : ?>
    <div class="row">
<? endif; ?>
    <div class="large-6 columns">
        <? echo $this->row->type . '<br>'; ?>
        <? if ($this->row->type == 'datalist') : ?>
            {I template=Form_selectlist model_name=<?= $list; ?> I}
        <? else : ?>
            {I template=Form_<? echo trim(strtolower($this->row->type)); ?> model_type=plugin_data model_name=<?= trim(
                strtolower($this->row->template_view)
            ); ?> field_name=<?= trim($this->row->name); ?> I}
        <? endif; ?>
    </div>
<? if ($this->row->even_or_odd == 'odd') : ?>
<? else : ?>
    </div>
<? endif;
