<?
/**
 * Gridtags Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
if ($this->row->enable == 1) {
    ?>
    <div class="grid-tags grid-batch">
        <ol class="grid-batch">
            <li><strong><? echo $this->language_controller->translate('Tags Assignment'); ?></strong></li>
            <li>
                <include formselectlist datalist=tags/>
            </li>
            <li><input type="submit" class="submit button small radius" name="submit" id="AssignTags" value="Assign">
            </li>
            <li><input type="submit" class="submit button small radius" name="submit" id="RemoveTags" value="Remove">
            </li>
        </ol>
    </div>
<?
}
