<?
/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<form>
    <nav class="row">
        <div class="large-7 columns">
            <ul class="button-group">
                <li><span data-tooltip class="has-tip" title="New">
                        <a href="#" class="radius tiny button">
                            <i class="fi-page-add" alt="New"></i>
                        </a>
                    </span>
                </li>
                <li><span data-tooltip class="has-tip" title="Access">
                        <a href="#" class="radius tiny button">
                            <i class="fi-torsos-all" alt="Access"></i>
                        </a>
                    </span>
                </li>
                <li><span data-tooltip class="has-tip" title="Copy">
                        <a href="#" class="radius tiny button">
                            <i class="fi-page-copy" alt="Copy"></i>
                        </a>
                    </span>
                </li>
                <li><span data-tooltip class="has-tip" title="Filter">
                        <a href="#" class="radius tiny button">
                            <i class="fi-filter" alt="Filter"></i>
                        </a>
                    </span>
                </li>
                <li><span data-tooltip class="has-tip" title="Categorize">
                        <a href="#" class="radius tiny button">
                            <i class="fi-map" alt="Categorize"></i>
                        </a>
                    </span>
                </li>
                <li><span data-tooltip class="has-tip" title="Tag">
                        <a href="#" class="radius tiny button">
                            <i class="fi-price-tag" alt="Tag"></i>
                        </a>
                    </span>
                </li>
            </ul>
        </div>
        <div class="large-5 columns">
            <ul class="button-group">
                <li>
                    <select>
                        <option value="">Actions</option>
                        <option value="archive">Archive</option>
                        <option value="checkin">Check-in</option>
                        <option value="feature">Feature</option>
                        <option value="publish">Publish</option>
                        <option value="restore">Restore</option>
                        <option value="sticky">Sticky</option>
                        <option value="trash">Trash</option>
                        <option value="unpublish">Unpublish</option>
                    </select>
                </li>
                <li>
                    <span data-tooltip class="has-tip" title="Apply Action from List">
                        <a href="#" class="radius tiny button">
                            Apply
                        </a>
                    </span>
                </li>
            </ul>
        </div>
    </nav>
</form>
