<?
/**
 * Section Wrap View
 *
 * @package    Molajo\Themes\System
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */


$header_id = trim($this->runtime_data->wrap_view_css_id);
if ($header_id == '') :
else :
    $header_id = ' id="' . $header_id . '"';
endif;

$header_class = trim($this->runtime_data->wrap_view_css_class);
if ($header_class == '') :
else :
    $header_class = ' class="' . $header_class . '"';
endif;
?>
<form<?= $header_id; ?><?= $header_class; ?> method="post" action="<?=
$this->registry->get(
    'Page',
    'page_url'
); ?>">
