<?
/**
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<h3>Categories</h3>

<ul class="side-nav">
    <li><a href="#">News</a></li>
    <li><a href="#">Code</a></li>
    <li><a href="#">Design</a></li>
    <li><a href="#">Fun</a></li>
    <li><a href="#">Weasels</a></li>
</ul>
{I template=Featured wrap=Div wrap_class=panel I}
