<?
/**
 * Formselect Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

$tooltip_css_class = 'has-tip'; ?>
    <span class="<? echo $tooltip_css_class; ?>" title="<? echo $this->row->tooltip; ?>">
<label for="<? echo $this->row->field_id; ?>"><? echo $this->row->label; ?></label></span>
<select id="<? echo $this->row->field_id; ?>"
        name="<? echo $this->row->name; ?>"<? echo $this->row->multiple; ?> <? echo $this->row->required; ?> <? echo $this->row->disabled; ?> <? echo $this->row->size; ?>>
<? if ($this->row->multiple == '') { ?>
    <option value=""><? echo $this->language_controller->translate(
            'SELECT_' . strtoupper($this->row->datalist)
        ); ?></option>
<? } else { ?>
    <option value=""><? echo $this->language_controller->translate('No selection'); ?></option>
    <? if ($this->row->selected == '#') {

        $selected = ' selected';
    } else {
        $selected = '';
    }?>
    <option<? echo $selected; ?> value="#"><? echo $this->language_controller->translate('Select all'); ?></option>
<?
}
