<?
/**
 * Form Input Date Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
if (isset($this->row->locked) && (int) $this->row->locked === 1) :
    $readonly = ' readonly';
else :
    $readonly = '';
endif;
?>
<span data-tooltip class="has-tip" title="{T <?= $this->row->name; ?> T}">
    <label for="<?= $this->row->name; ?>">
        {T <?= $this->row->name; ?> T}
    </label>
</span>
<input type="date" name="<?= $this->row->name; ?>" value="<?= $this->row->value; ?>"<?= $readonly; ?>/>
