<?
/**
 * Assetcssdeclarations Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
$application_html5 = $this->row->application_html5;
$end = $this->row->end; ?>
    <style<? if ((int)$application_html5 == 0): ?>
    type="<? echo $this->row->mimetype; ?>"<? endif; ?><? echo $end; ?>
<? if ($this->row->page_mimetype == 'text/html') :
else : ?>
    <![CDATA[
<? endif;
echo $this->row->content . chr(10);
if ($this->row->page_mimetype == 'text/html') :
else : ?>
    ]]>
<?
endif; ?>
    </style><? echo chr(10);
