<?
/**
 * @package     Molajo
 * @subpackage  Views
 * @copyright   2013 Amy Stephen. All rights reserved.
 * @license     http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row-fluid">
    <div class="span4">
        <h2>Heading</h2>

        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
            condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
            Donec sed odio dui. </p>

        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
    <!--/span-->
    <div class="span4">
        <h2>Heading</h2>

        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
            condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
            Donec sed odio dui. </p>

        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
    <!--/span-->

    <div class="span4">
        <h2>Heading</h2>

        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
            condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
            Donec sed odio dui. </p>

        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
    <!--/span-->
</div><!--/row-->
<div class="row-fluid">

    <div class="span4">
        <h2>Heading</h2>

        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
            condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
            Donec sed odio dui. </p>

        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
    <!--/span-->
    <div class="span4">
        <h2>Heading</h2>

        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
            condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
            Donec sed odio dui. </p>

        <p><a class="btn" href="#">View details &raquo;</a></p>
    </div>
    <!--/span-->
    <div class="span4">
        <h2>Heading</h2>

        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
            condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
            Donec sed odio dui. </p>

        <p><a class="btn" href="#">View details &raquo;</a></p>

    </div>
    <!--/span-->
</div><!--/row-->
