<?
/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<a id="top"></a>
<!-- Nav Bar -->

<div class="row">
    <div class="large-12 columns">
        <div class="nav-bar right">
            <ul class="button-group">
                <li><a href="#" class="button">Link 1</a></li>
                <li><a href="#" class="button">Link 2</a></li>
                <li><a href="#" class="button">Link 3</a></li>
                <li><a href="#" class="button">Link 4</a></li>
            </ul>
        </div>
        <h1>Blog
            <small>This is my blog. It's awesome.</small>
        </h1>
        <hr/>
    </div>
</div>

<!-- End Nav -->

<div class="row">

    <!-- Main Content Section -->
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <article class="large-9 push-3 columns">

        <include Article class=right,secondary,small,button wrap=section role=main/>
            <? if ((int)$this->runtime_data->resource->parameters->enable_response_comments == 1) { ?>
                <aside class="row" role="complementary">
                    <div class="twelve rows">

                        <ul class="link-list right">
                            <a class="webicon facebook small" href="#">Facebook</a>
                            <a class="webicon mail small" href="#">Mail</a>
                            <a class="webicon twitter small" href="#">Twitter</a>
                        </ul>
                        <hr/>
                        <include Author wrap=Div wrap_class=author-profile/>
                            <section>
                                <include Comment/>
                                <include Comments/>
                                <include Commentform/>
                            </section>
                    </div>
                </aside>
            <? } ?>

            <include Paging wrap=nav role=navigation wrap_class=paging/>
    </article>

    <!-- Nav Sidebar -->
    <!-- This is source ordered to be pulled to the left on larger screens -->
    <div class="large-3 pull-9 columns">

        <ul class="side-nav">
            <li><a href="#">Section 1</a></li>
            <li><a href="#">Section 2</a></li>
            <li><a href="#">Section 3</a></li>
            <li><a href="#">Section 4</a></li>
            <li><a href="#">Section 5</a></li>
            <li><a href="#">Section 6</a></li>
        </ul>

        <p><img src="http://placehold.it/320x240&text=Ad"/></p>

    </div>

</div>
