<?
/**
 * 404 Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<div class="row">
    <div class="twelve columns">
        <? echo $this->row->content_text; ?>
    </div>
</div>

<div class="row">
    <div class="twelve columns">
        <include Author/>
    </div>
</div>
