<?
/**
 * Comments Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
$pageURL = $runtime_data->page->urls['page'];
?>
<article
    class="<? //echo trim('comment' . ' ' . $row->first_row . ' ' . $row->last_row . ' ' . $row->even_or_odd_row  . ' ' . $row->css_class); ?>"
    id="<? echo $row->alias; ?>">
    <div class="comment-meta">
        <a class="permalink" href="<? echo $pageURL; ?>#<? echo $row->alias; ?>">#</a>
        <? //echo $this->language_controller->translate('On') . ' ' ?>
        <time datetime="<? echo $row->created_datetime; ?>" pubdate>
            <? //echo $row->created_datetime_month_name
            // . ' ' . $row->created_datetime_day_number
            //  . ', ' . $row->created_datetime_ccyy
            //  . ', ' . $this->language_controller->translate('at')
            //  . ' ' . $row->created_datetime_time;
            ?>
        </time>
        ,
        <? //if ($row->website == '') {
        //       } else {
        ?>
        <a href="<? //echo $row->website; ?>" rel='external nofollow' class='url'>
            <? //} ?>
            <? //echo $row->customfields->visitor_name; ?>
            <? //if ($row->website == '') {
            // } else {
            ?>
        </a>
        <?
        //}
        // echo $this->language_controller->translate('said:') . ' ';
        ?>
        <? if ($row->title == '') {
        } else {
            ?>
            <header>
                <h5><? echo $row->title; ?></h5>
            </header>
        <? } ?>
    </div>
    <img alt=""
         src="http://1.gravatar.com/avatar/37372c3acc31affca29886c1a9cbc13b?s=48&amp;d=http%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D48&amp;r=G"
         class="gravatar float_right" height="48" width="48"/>

    <div class="comment-text">
        <p class="comment-text"><? echo $row->content_text; ?></p>
    </div>
</article>
