<?
/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */

/** Get menu id for level currently being processed */
$i = 1;
$currentMenuArray = array();

$menu = $this->runtime_data->page->menu['Menuadmin'];
$breadcrumbs = $this->runtime_data->page->breadcrumbs;
$pageURL = $this->runtime_data->page->urls['page'];

if (isset($menu[0]->css_class)) {
    $class = ' class="' . $menu[0]->css_class . '" ';
}
$link_text = $menu[0]->link_text;
$link = $menu[0]->link;
?>
<div class="fixed contain-to-grid" id="navigation-bar" role="banner">
    <nav class="top-bar">
        <ul>
            <li class="name">
                <h1>
                    <li<? echo $class; ?>><a href="<? echo $link; ?>"><? echo $link_text; ?></a>
                </h1>
            </li>
            <li class="toggle-topbar"><a href="<? echo $this->runtime_data->page->urls['page']; ?>#"></a>
            </li>
        </ul>
        <? if (count($menu) == 0 || $menu == '') {
        } else {
            ?>
            <section>
                <ul class="left">
                    <li class="divider"></li>
                    <?
                    $previous_lvl = 0;
                    foreach ($menu as $menuitem) {

                    /* Previous Menu Item(s) */
                    if ($previous_lvl == 0) {
                    } elseif ($previous_lvl == $menuitem->lvl) {
                        ?>
                        </li>

                    <?
                    } elseif ($previous_lvl < $menuitem->lvl) {
                    }
                    else {
                    $count = (int)$previous_lvl - (int)$menuitem->lvl + 1;
                    for ($i = 0;
                    $i < $count;
                    $i ++) {
                    if ($i + 1 == $count) {
                        ?>
                        </li>
                    <? } else { ?>
                    </li>
                </ul>
                <?
                }
                }
                }

                /* Current Menu Item */
                if (trim($menuitem->css_class) == '') {
                    $class      = '';
                    $extraclass = '';
                } else {
                    $class      = ' class="' . $menuitem->css_class . '" ';
                    $extraclass = ' ' . $menuitem->css_class;
                }

                $ulClass = '';
                $liClass = '';
                if ((int)$menuitem->lft + 1 == (int)$menuitem->rgt) {
                    if (trim($extraclass) == '') {
                    } else {
                        $ulClass = ' class="' . $extraclass . '"';
                        $liClass = ' class="' . $extraclass . '"';
                    }
                } else {
                    $ulClass = ' class="' . 'dropdown' . $extraclass . '"';
                    $liClass = ' class="' . 'has-dropdown' . $extraclass . '"';
                }

                if ($menuitem->lvl == 2) {
                $saveLvlLink  = '';
                $saveLvlTitle = '';
                ?>
            <li<? echo $liClass; ?>><a href="<? echo $menuitem->link; ?>"><i
                    class="<? echo $menuitem->subtitle; ?>"></i><span
                    class="small-device"><? echo $menuitem->title; ?></span></a>
            <? } else { ?>
                <li<? echo $liClass; ?>><a
                        href="<? echo $menuitem->link; ?>"><? echo $menuitem->link_text; ?></a>
                    <?
                    }

                    if ((int)$menuitem->lvl == 3) {
                        $saveLvlLink  = $menuitem->link;
                        $saveLvlTitle = $menuitem->link_text;
                    }

                    if ((int)$menuitem->lft + 1 == (int)$menuitem->rgt) {
                    } else {
                    ?>
                    <ul<? echo $ulClass; ?>>
                        <?
                        }

                        /** Save the current level */
                        $previous_lvl = $menuitem->lvl;
                        }
                        $count = (int)$previous_lvl - 1;
                        for ($i = 0;
                        $i < $count;
                        $i ++) {
                        if ($i + 1 == $count) {
                        ?>
                </li>
            <? } else { ?>
                </li>
                </ul>
            <?
            }
            } ?>
                </ul>
            </section>
        <? } ?>
        <section>
            <ul class="right">
                <li class="divider"></li>
                <li><a href="profile"><i class="icon-user"></i>&nbsp;<? //echo $registry->get(
                        //                'User',
                        //               'username'
                        //         );
                        ?></a></li>
                <li class="divider"></li>
                <li><a href="logout"><i class="icon-cog"></i></a></li>
                <li class="divider"></li>
                <li class="search">
                    <input type="text" name="search">
                </li>
                <li><a href="search"><i class="icon-search"></i></a></li>
            </ul>
        </section>
    </nav>
</div>
