<?
/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */

/** Get menu id for level currently being processed */
$i = 1;
$currentMenuArray = array();

$menu = $this->runtime_data->page->menu['Menuadmin'];

$breadcrumbs = $this->runtime_data->page->breadcrumbs;
$pageURL = $this->runtime_data->page->urls['page'];
$homeURL = $this->runtime_data->page->urls['home'];


/** Home */
$link_text = $menu[0]->title;
$link = $homeURL;

/** Profile */
$profile_link = '';
?>
<div class="fixed contain-to-grid" id="navigation-bar" role="banner">
    <nav class="top-bar" data-topbar>
        <ul class="title-area">
            <li class="name">
                <h1><a href="<? echo $link; ?>"><? echo $link_text; ?></a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
            <!-- Left Nav Section -->
            <ul class="left">
            <?

            $count = 0;
            $previous_level = 0;

            foreach ($menu as $menuitem) {

                /** Level 1: Home (skip) */
                if ((int)$menuitem->lvl == 1) {

                /** Level 2: Resources, Media, Access, Build, System (Dashboard) */
                } elseif ((int)$menuitem->lvl == 2) {

                    /** End Previous */
                    if ($previous_level == 1) {

                    } elseif ($previous_level == 4) { ?>
                    </ul>
                        </li>
                    </ul>
                        </li>

                    <?
                    } else { ?>
                    </ul>
                        </li>
                    <?
                    }
                    /* Start Level 2 */ ?>
                    <li class="divider"></li>
                    <li class="has-dropdown">
                        <a href="<? echo $menuitem->link; ?>" class="">
                            <i class="<? echo $menuitem->link_text; ?>" alt="<? echo $menuitem->title; ?>"></i>
                        </a>
                        <ul class="dropdown">

                <?
                /** Level 3: Articles, Pages, Contacts, Comments, Categories, Tags, Images, Files, etc. */
                } elseif ((int)$menuitem->lvl == 3) {

                    if ($previous_level == 4) { ?>
                        </ul>
                    </li>
                <?
                    } ?>
                    <li class="has-dropdown">
                        <a href="<? echo $menuitem->link; ?>"><? echo $menuitem->link_text; ?></a>
                        <ul class="dropdown">
                <?
                } else { ?>
                    <li><a href="<? echo $menuitem->link; ?>"><? echo $menuitem->link_text; ?></a></li>
             <? }
                $previous_level = $menuitem->lvl;
                $count++;
            } ?>
            </ul>
        </section>

        <section class="top-bar-section">
            <ul class="right">
                <li class="divider"></li>
                <li class="has-dropdown">
                    <a href="<? echo $profile_link; ?>" class="">
                        <i class="fi-torso" alt="Profile"></i>
                    </a>
                    <ul class="dropdown">
                        <li><a href="#">Password</a></li>
                        <li><a href="#">Profile</a></li>
                        <li><a href="#">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </section>
    </nav>
</div>
