<?
/**
 * Comments Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
{I template=Comments_heading source_id=<?= $this->row->source_id ?> I}
{I template=Comments_list source_id=<?= $this->row->source_id ?> I}
{I template=Comments_form source_id=<?= $this->row->source_id ?> I}
