<?
/**
 * Pagination Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<nav class="row pagination-centered">
    <div class="large-12 small-12 columns">
        <ul class="pagination">
            <li class="arrow unavailable"><a href="">First</a></li>
            <li class="arrow unavailable"><a href="">&laquo;</a></li>
            <? $current = ' class="current"';
            for (
                $i = 1;
                $i < 5;
                $i++
            ) {
                ?>
                <li<?= $current; ?>><a href=""><?= $i; ?></a></li>
                <?
                $current = '';
            } ?>
            <li class="arrow unavailable"><a href="">&raquo;</a></li>
            <li class="arrow unavailable"><a href="">Last</a></li>
        </ul>
    </div>
</nav>
