<?
/**
 * Pagination Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
if (isset($this->plugin_data->pagination)) :
    $pagination = $this->plugin_data->pagination; ?>
    <nav class="row pagination-centered">
        <div class="large-12 small-12 columns">
            <ul class="pagination">
                <li class="arrow unavailable"><a href="<?= $pagination->getPageUrl('first'); ?>">First</a></li>
                <li class="arrow unavailable"><a href="<?= $pagination->getPageUrl('prev'); ?>">&laquo;</a></li>
                <? $current = ' class="current"';
                for (
                    $i = $pagination->getStartDisplayPage();
                    $i < $pagination->getStopDisplayPage();
                    $i++
                ) {
                    ?>
                    <li<?= $current; ?>><a href="<?= $pagination->getPageUrl($i); ?>"><?= $i; ?></a></li>
                    <?php
                    $current = '';
                } ?>
                <li class="arrow unavailable"><a href="<?= $pagination->getPageUrl('next'); ?>">&raquo;</a></li>
                <li class="arrow unavailable"><a href="<?= $pagination->getPageUrl('last'); ?>">Last</a></li>
            </ul>
        </div>
    </nav>
<? endif;
