<?
/**
 * Feed Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<p>
    <a href="<?= $this->row->link; ?>">
        <strong><?= $this->row->title; ?></strong>
    </a>
    <? if ($this->runtime_data->display_snippet == 1) : ?>
        <br><?= $this->row->description; ?>
    <? endif;
    if ($this->runtime_data->display_published_date == 1) : ?>
        <br><strong>{T Published T}: </strong><?= $this->row->published_date; ?>
    <? endif; ?>
</p>
