<?
/**
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */

if ((int)$this->row->comments_open == 1) : ?>
    {I template=Form_begin form_name=comments I}
    <div class="row">
        <fieldset id="reply">
            <legend>{T Your Response T}</legend>

            <div class="row">
                <div class="large-2 columns">
                    <label for="visitor_name" class="required right inline">
                        {T Name T}:
                    </label>
                </div>
                <div class="large-10 columns">
                    <input id="visitor_name" name="visitor_name" required type="text" placeholder="{T First and Last Name T}"/>
                </div>
            </div>

            <div class="row">
                <div class="large-2 columns">
                    <label for="email_address" class="required right inline">
                        {T Email T}:
                    </label>
                </div>
                <div class="large-10 columns">
                    <input id="email_address" name="email_address" required type="email" placeholder="{T Your email address will not be published. T}"/>
                </div>
            </div>

            <div class="row">
                <div class="large-2 columns">
                    <label for="website" class="right inline">
                        {T Website T}:
                    </label>
                </div>
                <div class="large-10 columns">
                    <input id="website" name="website" type="url" placeholder="{T Website will be shared with site visitors. T}"/>
                </div>
            </div>

            <div class="row">
                <div class="large-2 columns">
                    <label for="comment" class="required right inline">
                        {T Comment T}:
                    </label>
                </div>
                <div class="large-10 columns">
                    <textarea id="comment" name="comment" required placeholder="{T Your response... T}"></textarea>
                </div>
            </div>

            <div class="row">
                <div class="large-8 columns">
                    <label class="right inline"></label>
                </div>
                <div class="large-4 columns">
                    <button class="[radius, round] button right">{T Save T}</button>
                </div>
            </div>

            <input name="id" type="hidden" value="<?= $this->row->id ?>"/>
            <input name="model_name" type="hidden" value="Comments"/>
            <input name="model_type" type="hidden" value="Resource"/>
        </fieldset>
        {I template=Form_end I}
    </div>
<? endif;
