<?
/**
 * Contentlist Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<p>
    <a href="<?= $this->row->catalog_id_url; ?>"><strong><?= $this->row->title; ?></strong></a>
    <? if ($this->runtime_data->display_snippet == 1) : ?>
        <br><?= $this->row->content_text_snippet; ?>
    <? endif;
    if ($this->runtime_data->display_author_name == 1) : ?>
        <br><strong>{T Written by T}:</strong><?= $this->row->author_full_name; ?>
    <? endif;
    if ($this->runtime_data->display_published_date == 1) : ?>
        <br><strong>{T Published T}:</strong><?= $this->row->start_publishing_datetime_pretty_date; ?>
    <? endif; ?>
</p>
