<?
/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<header id="header-page" class="contain-to-grid not-small-device" role="banner">
    <div class="row">
        <div class="page-menu">
            <ul class="page-menu">
                <li>
                    <a href="<? echo $this->runtime_data->page->urls['page']; ?>">
                        <? echo $this->runtime_data->page->heading1 ?>
                    </a>
                </li>
                <?
                $pageSubmenu = $this->runtime_data->page->menu['PageSubmenu'];
                if (count($pageSubmenu) > 0) {
                    foreach ($pageSubmenu as $menu) {
                        if ((int)$menu->current == 1) {
                            $active = ' class="active"';
                        } else {
                            $active = '';
                        }
                        ?>
                        <li>
                            <a<? echo $active; ?> href="<? echo $menu->link; ?>">
                                [ <? echo $menu->link_text; ?> ]
                            </a>
                        </li>
                    <? } ?>
                <? } ?>
            </ul>
        </div>
    </div>
    <?
    $pageArray = $this->runtime_data->page->menu['SectionSubmenu'];
    $count = count($pageArray);
    if ($count > 0) {
        ?>
        <div class="row">
            <div class="section-submenu">
                <ul class="section-submenu">
                    <li>
                        <strong><? echo $this->language->translate('Options') . ': '; ?></strong>
                    </li>
                    <?
                    foreach ($pageArray as $pages) {
                        if ((int)$pages->current == 1) {
                            $active = ' class="active"';
                        } else {
                            $active = '';
                        } ?>
                        <li>
                            <a<? echo $active; ?> id="<? echo $pages->id; ?>" href="<? echo $pages->url; ?>">
                                <? echo $pages->title; ?>
                            </a>
                        </li>
                    <?
                    }
                    ?>
                </ul>
            </div>
        </div>
    <? } ?>
</header>
<header id="header-page" class="small-device" role="banner">
    <div class="row">
        <div class="page-menu">
            <ul class="page-menu">
                <?
                $pageSubmenu = $this->runtime_data->page->menu['PageSubmenu'];
                $i = 0;
                if (count($pageSubmenu) > 0) {
                    foreach ($pageSubmenu as $menu) {
                        if ((int)$menu->current == 1) {
                            $active = ' class="active"';
                        } else {
                            $active = '';
                        }
                        if ($i == 0) {
                            $text = $this->runtime_data->page->heading1;
                        } else {
                            $text = '[ ' . $menu->link_text . '] ';
                        }
                        $i ++;
                        ?>
                        <li>
                            <a<? echo $active; ?> href="<? echo $menu->link; ?>">
                                <? echo $text; ?>
                            </a>
                        </li>
                    <? } ?>
                <? } ?>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="section-submenu">
            <ul class="section-submenu">
                <?
                $pageArray = $this->runtime_data->page->menu['SectionSubmenu'];
                $count = count($pageArray);

                if ($count > 0) {
                    foreach ($pageArray as $pages) {
                        if ((int)$pages->current == 1) {
                            $active = ' class="active"';
                        } else {
                            $active = '';
                        }
                        ?>
                        <li>
                            <a<? echo $active; ?> id="<? echo $pages->url; ?>" href="<? echo $pages->url; ?>">
                                <? echo $pages->title; ?>
                            </a>
                        </li>
                    <?
                    }
                }
                ?>
            </ul>
        </div>
    </div>
</header>
