<?
/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<include Breadcrumbs/>
<div class="row">
    <header class="large-4 columns">
        <h3>Articles</h3>
    </header>
    <nav class="large-8 columns">
        <include Toolbar/>
    </nav>
</div>
<div id="grid-filters" class="row">
    <include Gridfilters/>
</div>
