<br>
<div class="row">
    <div class="large-12 columns">

        <div class="row">
            <div class="large-4 columns">

                <div class="hide-for-small panel">
                    <h3>Resources</h3>
                    <h5 class="subheader">Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna.
                    </h5>
                    <ul class="side-nav">
                        <li><a href="/admin/comments">Hierarchy</a></li>
                        <li><a href="/admin/articles">Financials</a></li>
                        <li><a href="/admin/pages">Human Resources</a></li>
                        <li><a href="/admin/contacts">Student System</a></li>
                    </ul>
                </div>
            </div>

            <!-- End Side Bar -->

            <!-- Thumbnails -->

            <div class="large-8 columns">
                <div class="row">

                    <div class="large-4 small-6 columns">
                        <div class="panel">
                            <h5>Unassigned Cost Objects</h5>

                            <p class="small">The following cost objects are not assigned to the current academic year
                                and primary organizational unit.</p>
                            <ul>
                                <li><a href="/admin/articles/article-17/edit">91-4425-0100</a></li>
                                <li><a href="/admin/articles/article-19/edit">91-4440-0100</a></li>
                                <li><a href="/admin/articles/article-4/edit">94-5555-4444</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="large-4 small-6 columns">
                        <div class="panel">
                            <h5>HR Code Assignments</h5>

                            <p class="small">The following human resource codes are not assigned to the current academic
                                year and primary organizational unit.</p>
                            <ul>
                                <li><a href="/admin/pages/about-us/edit">111111</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="large-4 small-6 columns">
                        <div class="panel">
                            <h5>Student System Code Assignments</h5>

                            <p class="small">The following student information system codes are not assigned to the
                                current academic year and primary organizational unit.</p>
                            <ul>
                                <li><a href="/admin/contacts/contact-4">44-444</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="large-12 columns">
                        <div class="panel">
                            <h5>Recent Data Dictionary Entries</h5>
                            <ul>
                                <li><a href="#">academic_or_fiscal_year</a></li>
                                <li><a href="#">university_class_group</a></li>
                                <li><a href="#">wage_type</a></li>
                                <li><a href="#">planning_status</a></li>
                                <li><a href="#">marital_status</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="large-12 columns">
                        <div class="panel">
                            <h5>Access</h5>
                            <ul>
                                <li><a href="#">Account</a></li>
                                <li><a href="#">Access Control</a></li>
                                <li><a href="#">Users</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
