<?
/**
 * Portlet Wrap View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
?>
<div class="portlet-header">
    <? if ($runtime_data->criteria_title == '') {
    } else {
        ?>
        <h4><? echo $runtime_data->criteria_title; ?></h4>
    <? } ?>
</div>
<div class="portlet-content">
