<?
/**
 * Assetsjsdeclarations Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
$application_html5 = $this->row->application_html5;
$end = $this->row->end;
?>
<script<? if ((int)$application_html5 == 0): ?> type="<? echo $this->row->mimetype; ?>"<? endif; ?>>
    <?
    if ($this->row->page_mimetype == 'text/html') :
    else : ?>
    <![CDATA[
    <?
endif;
echo '    ' . trim($this->row->content) . chr(10);
if ($this->row->page_mimetype == 'text/html') :
else : ?>
    ]]>
    <?
endif; ?>
</script><? echo chr(10);
