<?
/**
 * Default Wrap View
 *
 * @package    Molajo\Themes\System
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */

if ((int)$this->runtime_data->application->parameters->application_html5 == 1
    && ($this->row->wrap_name == 'Article'
        || $this->row->wrap_name == 'Aside'
        || $this->row->wrap_name == 'Footer'
        || $this->row->wrap_name == 'Header'
        || $this->row->wrap_name == 'Hgroup'
        || $this->row->wrap_name == 'Nav'
        || $this->row->wrap_name == 'Section')
) :
    $header_type = $this->row->wrap_name;
else :
    $header_type = 'div';
endif;
$header_type = strtolower($header_type);
?>
</<?= $header_type; ?>>
