<?
/**
 * Default Wrap View
 *
 * @package    Molajo\Themes\System
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
if ($this->row->wrap_name == 'Article'
        || $this->row->wrap_name == 'Aside'
        || $this->row->wrap_name == 'Footer'
        || $this->row->wrap_name == 'Header'
        || $this->row->wrap_name == 'Hgroup'
        || $this->row->wrap_name == 'Nav'
        || $this->row->wrap_name == 'Section'):
    $header_type = $this->row->wrap_name;
else :
    $header_type = 'div';
endif;
$header_type = strtolower($header_type);

$header_id = trim($this->plugin_data->render->extension->parameters->wrap_view_css_id);
if ($header_id == '') :
else :
    $header_id = ' id="' . $header_id . '"';
endif;

$header_class = trim($this->plugin_data->render->extension->parameters->wrap_view_css_class);
if ($header_class == '') :
else :
    $header_class = ' class="' . $header_class . '"';
endif;

$header_role = trim($this->plugin_data->render->extension->parameters->wrap_view_role);
if ($header_role == '') :
else :
    $header_role = ' role="' . $header_role . '"';
endif;

$header_property = trim($this->plugin_data->render->extension->parameters->wrap_view_property);
if ($header_property == '') :
else :
    $header_property = ' property="' . $header_property . '"';
endif;
?>
    <<?= trim($header_type . $header_id . $header_class . $header_role . $header_property); ?>>
<?
$heading_level = $this->plugin_data->render->extension->parameters->wrap_view_header_level;
if ((int)$this->runtime_data->application->parameters->application_html5 == 1):
    if ($this->plugin_data->render->extension->parameters->wrap_view_show_title === true
        && $this->plugin_data->render->extension->parameters->wrap_view_show_subtitle === true
    ) : ?>
        <hgroup>
    <? endif;
endif;

if ($this->plugin_data->render->extension->parameters->wrap_view_show_title === true) :  ?>
    <h<?= $heading_level; ?>>
        <?= $this->row->title; ?>
    </h<?= $heading_level++; ?>>
<?
endif;

if ($this->plugin_data->render->extension->parameters->wrap_view_show_subtitle === true) :  ?>
    <h<?= $heading_level; ?>>
        <?= $this->row->subtitle; ?>
    </h<?= $heading_level++; ?>>
<?
endif;

if ((int)$this->runtime_data->application->parameters->application_html5 == 1) :
    if ($this->plugin_data->render->extension->parameters->wrap_view_show_title === true
        && $this->plugin_data->render->extension->parameters->wrap_view_show_subtitle === true
    ) : ?>
        </hgroup>
    <? endif;
endif;
