<?
/**
 * Form Boolean Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
if ((int)$this->row->value === 0) :
    $on_checked  = '';
    $off_checked = 'checked ';
else :
    $on_checked  = 'checked ';
    $off_checked = '';
endif; ?>
    <span data-tooltip class="has-tip" title="{T <?= $this->row->name; ?> T}">
    <label>
        {T <?= $this->row->name; ?> T}
    </label>
</span>
<? if (isset($this->row->locked) && (int)$this->row->locked === 1) : ?>
    <input type="hidden" name="<?= $this->row->name; ?>" value="<?= $this->row->value; ?>"/>
    <? if ($this->row->value === 1) : ?>
        {T On T}
    <? else : ?>
        {T Off T}
    <? endif; ?>
<? else : ?>
    <input type="radio" <?= $on_checked; ?>name="<?= $this->row->name; ?>" value="1"
           id="<?= $this->row->name . '1'; ?>">
    <label for="<?= $this->row->name . '1'; ?>">{T On T}</label>
    <input type="radio" <?= $off_checked; ?>name="<?= $this->row->name; ?>" value="0"
           id="<?= $this->row->name . '0'; ?>">
    <label for="<?= $this->row->name . '0'; ?>">{T Off T}</label>
<? endif;
