<?
/**
 * Breadcrumbs Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<div class="row">
<?
if (count($this->runtime_data->page->breadcrumbs)) {
    $count = 0;
    foreach ($this->runtime_data->page->breadcrumbs as $breadcrumbs) {
        if ($count === 0) { ?>
            <ul class="breadcrumbs">
                <li><a href="#"><span>Home</span></a></li>
        <?
        } ?>
        <li><span><? echo $breadcrumbs->title; ?></span></li><?
    }
} ?>
</div>
