<?
/**
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */

/** Level 1: Home (skip) */
if ((int)$this->row->lvl == 1) :

/** Level 2: Resources, Media, Access, Build, System (Dashboard) */
elseif ((int)$this->row->lvl == 2) : /** End Previous */ {
    if ($this->row->previous_lvl == 1) :

    else : ?>
        </ul>
        </li>
        </ul>
        </li>
    <? endif; ?>
    <!-- Begin Level 2 -->
    <li class="divider"></li>
    <li class="has-dropdown">
    <a href="<?= $this->row->link; ?>" class="">
        <i class="<?= $this->row->link_text; ?>" alt="<?= $this->row->title; ?>"></i>
    </a>
    <!-- Begin Level 3 Dropsdown -->
    <ul class="dropdown">
<?
} /** Level 3: Articles, Pages, Contacts, Comments, Categories, Tags, Images, Files, etc. */
elseif ((int)$this->row->lvl == 3) :

    if ($this->row->previous_lvl == 2) :
    else : ?>
        <!-- End Level 3 Dropsdown -->
        </ul>
    <?  endif; ?>
    <li class="has-dropdown">
    <a href="<?= $this->row->link; ?>">
        <?= $this->row->link_text; ?>
    </a>
    <!-- Begin Level 4 Dropsdown -->
    <ul class="dropdown">
<?
else :  ?>
    <li>
        <a href="<?= $this->row->link; ?>">
            <?= $this->row->link_text; ?>
        </a>
    </li>
<? endif;
