<?
/**
 * @package     Molajo
 * @subpackage  Views
 * @copyright   2014-2015 Amy Stephen. All rights reserved.
 * @license     http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="hero-unit">
    <h1>Hello, world!</h1>

    <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero
        unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>

    <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>
