<?
/**
 * Formselect Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

$tooltip_css_class = 'has-tip'; ?>
    <span class="<? echo $tooltip_css_class; ?>" title="<? echo $row->tooltip; ?>">
<label for="<? echo $row->field_id; ?>"><? echo $row->label; ?></label></span>
<select id="<? echo $row->field_id; ?>"
        name="<? echo $row->name; ?>"<? echo $row->multiple; ?> <? echo $row->required; ?> <? echo $row->disabled; ?> <? echo $row->size; ?>>
<? if ($row->multiple == '') { ?>
    <option value=""><? echo $this->language_controller->translate(
            'SELECT_' . strtoupper($row->datalist)
        ); ?></option>
<? } else { ?>
    <option value=""><? echo $this->language_controller->translate('No selection'); ?></option>
    <? if ($row->selected == '#') {

        $selected = ' selected';
    } else {
        $selected = '';
    }?>
    <option<? echo $selected; ?> value="#"><? echo $this->language_controller->translate('Select all'); ?></option>
<?
}
