<!DOCTYPE html>
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Molajo</title>
    <link rel="stylesheet" href="/Css/normalize.css">
    <link rel="stylesheet" href="/Css/webicons.css">
    <link rel="stylesheet" href="/Css/foundation-icons.css" />
    <link rel="stylesheet" href="/Css/foundation.css">
    <link rel="stylesheet" href="/Css/customize.css">
    <link rel="stylesheet" href="/Css/responsive-tables.css" />
    <script src="/Js/vendor/custom.modernizr.js"></script>
</head>
<body>
    <include page=<?php echo $this->row->page_name; ?>/>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="/Js/foundation/foundation.js"></script>
    <script src="/Js/foundation/foundation.topbar.js"></script>
    <script src="/Js/foundation/foundation.tooltip.js"></script>
    <script src="/Js/responsive-tables.js"></script>
    <script>
        $(document).foundation();
    </script>
    <script>
        $(function () {
            $('.checkall').on('click', function () {
                $(this).closest('table').find(':checkbox').prop('checked', this.checked);
            });
        });
    </script>
</body>
</html>
