<?
/**
 * Application Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
$this->runtime_data = $this->row->fieldset_template_view_parameter; ?>
{I <?= ucfirst(strtolower($this->row->fieldset_template_view)); ?> parameter=<?= $this->runtime_data; ?> I}
