<?
/**
 * Head Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
$class = $this->registry->get('runtime_data', 'page_view_css_class');
if (trim($class) == '') :
    $class = '';
else :
    $class = ' class="' . htmlspecialchars($class) . '"';
endif;

$id = $this->registry->get('runtime_data', 'page_view_css_id');
if (trim($id) == '') :
    $id = '';
else :
    $id = ' id="' . htmlspecialchars($id) . '"';
endif;

$application_html5 = $this->row->application_html5;
$end               = $this->row->end;

$l = $this->row->language;
$d = $this->row->language_direction;
if ((int)$application_html5 == 1) : ?>
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js ie oldie"<?= trim($d); ?> lang="<?= trim($l); ?>"><![endif]-->
<!--[if IE 7]>
<html class="no-js ie ie7"<?= trim($d); ?> lang="<?= trim($l); ?>"><![endif]-->
<!--[if IE 8]>
<html class="no-js ie ie8"<?= trim($d); ?> lang="<?= trim($l); ?>"><![endif]-->
<!--[if IE 9]>
<html class="no-js ie ie9"<?= trim($d); ?> lang="<?= trim($l); ?>"><![endif]-->
<!--[if gt IE 9]><!-->
<html class="no-js"<?= trim($d); ?> lang="<?= trim($l); ?>"><!--<![endif]-->
<? else : ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
>
<html xmlns="http://www.w3.org/1999/xhtml" <?= $this->row->language_direction; ?>
      lang="<?= $this->row->language; ?>">
<? endif; ?>
<head>
    <title><?= $this->row->title; ?></title>
    <base href="<?= $this->row->base_url . '"' . $end; ?>
<? if ((int)$application_html5 == 1) : ?>
    <meta charset=" utf-8
    " <?= $end; ?>
    <? else : ?>
        <meta http-equiv="Content-Type"
        content="<?= $this->row->mimetype; ?>; charset=utf-8"<?= $end; ?>
    <?
    endif;
    ?>
    {I type=asset name=Assetslinks I}
    {I type=metadata name=Metadata I}
    {I type=asset name=Assetscss I}
    {I type=asset name=Assetscssdeclarations I}
    {I type=asset name=Assetsjs I}
    {I type=asset name=Assetsjsdeclarations I}
</head>
<body<?= $id; ?><?= $class; ?>>
