<?
/**
 * Author Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h5><? echo $this->row->full_name; ?></h5>
            <? if ($this->parameters->display_gravatar == 1) { ?>
                <p>
                    <img class="gravatar float_left" src="<? echo $this->row->email; ?>" itemprop="photo"
                         alt="[<? echo $this->row->full_name; ?>]">
                </p>
            <? } ?>
            <p>
                <a href="<? echo $this->row->sef_url; ?>"
                   title="<? echo $this->language_controller->translate('Posts by '); ?>
                    <span itemprop=" name">
                <? echo $this->row->full_name; ?>
                </span>
                </a>
            </p>
            <? if ($this->parameters->display_phone == 1) { ?>
                <p itemprop="tel">
                    <? echo $this->row->customfields->phone; ?>
                </p>
            <? } ?>
            <? if ($this->parameters->display_email == 1) { ?>
                <h5>
                    <? echo $this->row->email; ?>
                </h5>
            <? } ?>
            <p>
                <? echo $this->row->customfields->about_me; ?>
            </p>
        </div>
    </div>
</div>
