<?
/**
 * @package    Molajo
 * @copyright  2013 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="portlet-header">
    <h4>Quick Links</h4>
</div>
<div class="portlet-content">
    <ul>
        <li><a class="new article" href="#">New Article</a></li>
        <li><a class="unpublished comment" href="#">Unpublished Comments</a></li>
        <li><a class="media" href="#">Media</a></li>
        <li><a class="user" href="#">Add User</a></li>
        <li><a class="add resource" href="#">Add Resource</a></li>
        <li><a class="create extension" href="#">Create Extension</a></li>
    </ul>
</div>
