<?
/**
 * @package    Molajo
 * @copyright  2013 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="resource-toolbar">
    <a class="slider"><img alt="" id="bot"
                           src="Extension/Theme/Molajo/View/Template/Toolbar/Images/arrow_bottom.png"></a>
    <ul id="toolbar">
        <li><a href="#"><img src="Extension/Theme/Molajo/View/Template/Toolbar/Images/t1.png"/> Home</a></li>
        <li>
            <ul id="1">
                <li><a href="#"><img src="Extension/Theme/Molajo/View/Template/Toolbar/Images/empty.gif"/>Link 1</a>
                </li>
                <li><a href="#"><img src="Extension/Theme/Molajo/View/Template/Toolbar/Images/empty.gif"/>Link 2</a>
                </li>
                <li><a href="#"><img src="Extension/Theme/Molajo/View/Template/Toolbar/Images/empty.gif"/>Link 3</a>
                </li>
            </ul>
            <a href="#" class="sub" tabindex="1"><img
                    src="Extension/Theme/Molajo/View/Template/Toolbar/Images/t2.png"/>HTML/CSS</a>
        </li>
        <li>
            <ul id="2">
                <li><a href="#"><img src="Extension/Theme/Molajo/View/Template/Toolbar/Images/empty.gif"/>Link 6</a>
                </li>
                <li><a href="#"><img src="Extension/Theme/Molajo/View/Template/Toolbar/Images/empty.gif"/>Link 7</a>
                </li>
            </ul>
            <a href="#" class="sub" tabindex="1"><img
                    src="Extension/Theme/Molajo/View/Template/Toolbar/Images/t3.png"/>jQuery/JS</a>
        </li>
        <li><a href="#"><img src="Extension/Theme/Molajo/View/Template/Toolbar/Images/t2.png"/>PHP</a></li>
    </ul>
</div>
