<?
/**
 * Assetslinks Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */

$application_html5 = $this->row->application_html5;
$end               = $this->row->end;
?>
    <link href="<?= $this->row->url; ?>"
    rel="<?= $this->row->relation; ?>"<?=
$this->row->attributes; ?><?=
$end;
