<?
/**
 * Section Wrap View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */


$headerId = trim($this->runtime_data->wrap_view_css_id);
if ($headerId == '') :
else :
    $headerId = ' id="' . $headerId . '"';
endif;

$headerclass = trim($this->runtime_data->wrap_view_css_class);
if ($headerclass == '') :
else :
    $headerclass = ' class="' . $headerclass . '"';
endif;
?>
<form<? echo $headerId; ?><? echo $headerClass; ?> method="post" action="<? echo $this->registry->get(
    'Page',
    'page_url'
); ?>">
