<?
/**
 * Header Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-4 small-12 columns">
        <header>
            <h2>
                {T <?= $this->runtime_data->resource->parameters->criteria_title; ?> T}
            </h2>
        </header>
    </div>
    <div class="large-8 small-12 columns">
        {I template=Toolbar I}
    </div>
</div>
