<?
/**
 * Article Page View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<div class="row">
    <div id="main" class="article large-9 push-3 columns" role="main">
        {I Article I}
    </div>
    <div class="large-3 pull-9 columns">
        <ul class="side-nav">
            <li><a href="#">Section 1</a></li>
            <li><a href="#">Section 2</a></li>
            <li><a href="#">Section 3</a></li>
            <li><a href="#">Section 4</a></li>
            <li><a href="#">Section 5</a></li>
            <li><a href="#">Section 6</a></li>
        </ul>
        <p><img src="http://placehold.it/320x240&text=Ad"/></p>
    </div>
</div>
