<?
/**
 * Blog Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<article class="blog">
    <h3>
        <a href="<?= $this->row->catalog_sef_request; ?>">
            <?= $this->row->title; ?>
        </a>
    </h3>

    <h6>{T Written by T}
        <a href="#">
            <? echo $this->row->author_full_name; ?>
        </a>
        {T on T}
        <?=
        $this->row->start_publishing_datetime_day_name
        . ', ' . $this->row->start_publishing_datetime_month_name
        . ' ' . $this->row->start_publishing_datetime_dd
        . ', ' . $this->row->start_publishing_datetime_ccyy; ?>
    </h6>

    {I Image image_id=<?= $this->row->image_id1 ?> align=right size=M I}

    <? if (trim($this->row->content_text_introductory) === '') :
    else : ?>
        <div class="introductory">
            <?= $this->row->content_text_introductory; ?>
        </div>
    <? endif; ?>

    <p class="readmore">
        <a href="<?= $this->row->catalog_sef_request; ?>">
            {T Read more T}&rarr;
        </a>
    </p>
</article>
