<?
/**
 * Formpage Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */


if ($this->row->page_first_row == 1) {
} elseif ($this->row->new_fieldset == 1) {
    ?>
    </fieldset>
<?
}

if ($this->row->page_first_row == 1) {
} elseif ($this->row->page_subtitle_first_row == 1) {
    ?>
    </div>
<?
}

if ($this->row->page_subtitle_first_row == 1) {
?>
<hr/>
<div id="<? echo $this->row->page_subtitle; ?>" class="subtitle radius">
    <h4><? echo $this->row->page_subtitle; ?></h4>
    <? if ($this->runtime_data->application_help == 1) { ?>
        <h6><? echo $this->row->page_subtitle_description; ?></h6>
    <? } ?>
</div>
<hr/>
<div class="configuration-body">
    <?
    }

    if ($this->row->new_fieldset == 1) {
    ?>
    <fieldset class="configuration">
        <legend class="configuration"><? echo $this->row->fieldset_title; ?></legend>
        <? if ($this->runtime_data->application_help == 1) { ?>
            <p><? echo $this->row->fieldset_description; ?></p>
        <?
        }
        } ?>
        <include <? echo $this->row->view; ?> parameter_np=<? echo $this->row->name; ?>/>
