<?
/**
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
$page_url = $this->runtime_data->request->data->url;
$home_url = $this->runtime_data->application->base_url;
?>
<form name="configuration" id="configuration" method="post" data-abide>
    <nav class="row">
        <div class="large-12 columns">
            <ul class="button-group right">
                <li>
                    <button class="radius small button" id="Submit">
                        {T Save T}
                    </button>
                </li>
                <li>
                    <a id="alert-button" href="<?= $page_url; ?>" class="radius small alert button">
                        {T Reset T}
                    </a>
                </li>
            </ul>
        </div>
    </nav>
