<?
/**
 * Toolbar Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 *
 *             {I template=Form_selectlist model_name=datalist_actions I}
 *
 *             {I template=Form_buttongroup model_name=buttongroup_grid I}
 *
 */
?>
<nav class="row">
    <div class="large-5 columns">
        <ul class="button-group">
            <li>

            </li>
            <li>
                <span data-tooltip class="has-tip" title="{T Apply action to selected items in grid. T}">
                    <a href="#" class="radius tiny button">
                        {T Apply T}
                    </a>
                </span>
            </li>
        </ul>
    </div>
    <div class="large-7 columns">

    </div>
</nav>
