<?
/**
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<nav class="row">
    <div class="large-12 columns">
        <ul class="button-group right">
            <li>
                <span data-tooltip class="has-tip" title="{T Save T}">
                    <input type="submit" name="save" class="radius small button" value="{T Save T}" />
                </span>
            </li>
            <li>
                <span data-tooltip class="has-tip" title="{T Save As T}">
                    <input type="submit" name="saveas" class="radius small button" value="{T Save As T}" />
                </span>
            </li>
            <li>
                <span data-tooltip class="has-tip" title="{T Cancel T}">
                    <input type="submit" name="cancel" class="radius small button" value="{T Cancel T}" />
                </span>
            </li>
            <li>
                <span data-tooltip class="has-tip" title="{T Delete T}">
                    <input type="submit" name="delete" class="radius small button alert" value="{T Delete T}" />
                </span>
            </li>
        </ul>
    </div>
</nav>
