<?
/**
 * Toolbar Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<nav class="row">
    <div class="large-5 columns">
        <form method="post" action="" enctype="multipart/form-data">
            <ul class="button-group">
                <li>
                    {I template=Form_selectlist model_name=datalist_actions I}
                </li>
                <li>
                    <span data-tooltip class="has-tip" title="{T Apply action to selected items in grid. T}">
                        <a href="#" class="radius tiny button">
                            {T Apply T}
                        </a>
                    </span>
                </li>
            </ul>
        </form>
    </div>
    <div class="large-7 columns">
        {I template=Form_buttongroup model_name=buttongroup_grid I}
    </div>
</nav>
