<?
/**
 * Profile Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<h1><?= $this->row->username; ?></h1>

<p><strong>{T Username T}</strong>: <?= $this->row->username; ?></p>
<p><strong>{T First Name T}</strong>: <?= $this->row->first_name; ?></p>
<p><strong>{T Last Name T}</strong>: <?= $this->row->last_name; ?></p>
<p><strong>{T Full Name T}</strong>: <?= $this->row->full_name; ?></p>
<p><strong>{T Alias T}</strong>: <?= $this->row->alias; ?></p>
<p><strong>{T Text T}</strong>: <?= $this->row->content_text; ?></p>
<p><strong>{T Email T}</strong>: <?= $this->row->email; ?></p>
<p><strong>{T Blocked T}</strong>: <?= $this->row->block; ?></p>
<p><strong>{T Registered T}</strong>: <?= $this->row->register_datetime; ?></p>
<p><strong>{T Activated T}</strong>: <?= $this->row->activation_datetime; ?></p>
<p><strong>{T Last Visited T}</strong>: <?= $this->row->last_visit_datetime; ?></p>
