<?
/**
 * Customfields Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<div class="configuration-header">
    <header>
        <h3><? echo $this->row->page_title_extended; ?></h3>
        <? if ($this->runtime_data->application_help == 1) { ?>
            <h6><? echo $this->row->page_description; ?></h6>
        <? } ?>
    </header>
    <section>
        <ul class="inline-list right">
            <li><a href="#"><strong><? echo $this->language_controller->translate('Reset'); ?></strong></a></li>
            <li><a href="#" class="button success radius"><? echo $this->language_controller->translate(
                        'Save',
                        'Save'
                    ); ?></a></li>
        </ul>
    </section>
</div>

<include <? echo $this->row->view; ?> parameter_np=<? echo $this->row->name; ?>/>

<div class="configuration-body">

    <table class="responsive">
        <thead>
        <tr>
            <th class="create-type"><? echo $this->language_controller->translate('Criteria'); ?></th>
            <th class="create-value"><? echo $this->language_controller->translate('Value'); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="create-type"><? echo $this->language_controller->translate('Name'); ?></td>
            <td class="create-value">
                <input id="custom_field_name" type="text" placeholder="Customfield Name"/>
                <include Forminput id="custom_field_name" type="text"/>
            </td>
        </tr>
        <tr>
            <td class="create-type">
                <include formselect id="custom_field_type" datalist="datatype"/>
            </td>
        </tr>
        <tr>
            <td class="create-type"><? echo $this->language_controller->translate('Required'); ?></td>
            <td class="create-value"></td>
        </tr>
        <tr>
            <td class="create-type"><? echo $this->language_controller->translate('List'); ?></td>
            <td class="create-value"></td>
        </tr>
        <tr>
            <td class="create-type"><? echo $this->language_controller->translate('Hidden'); ?></td>
            <td class="create-value"></td>
        </tr>
        </tbody>
    </table>

    <table class="responsive">
        <thead>
        <tr>
            <th class="name"><? echo $this->language_controller->translate('Name'); ?></th>
            <th class="type"><? echo $this->language_controller->translate('Type'); ?></th>
            <th class="required"><? echo $this->language_controller->translate('Required'); ?></th>
            <th class="datalist"><? echo $this->language_controller->translate('List'); ?></th>
            <th class="hidden"><? echo $this->language_controller->translate('Hidden'); ?></th>
            <th width="1%">
                <? echo $this->language_controller->translate('Delete'); ?>
            </th>
        </tr>
        </thead>
        <tbody>
