<?
/**
 * Gridordering Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<div class="grid-ordering grid-batch">
    <ol class="grid-batch">
        <li><strong><? echo $this->language_controller->translate('Order Results'); ?></strong></li>
        <li>
            <include formselectlist datalist=Fields selected=<? echo $this->row->ordering; ?>/>
        </li>
        <li>
            <include formselectlist datalist=OrderingDirection selected=<? echo $this->row->direction; ?>/>
        </li>
        <li>
            <include formselectlist datalist=Itemsperpage selected=<? echo $this->row->items_per_page; ?>/>
        </li>
        <li><input type="submit" class="submit button small radius" name="submit" id="Sort" value="Sort"></li>
    </ol>
</div>
