<?
/**
 * Formradio Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

$tooltip_css_class = 'has-tip';
?>
<li>
    <input id="<? echo $this->row->id; ?>"<? echo $this->row->checked; ?> name="<? echo $this->row->name; ?>"
           type="radio">
    <label for="<? echo $this->row->id; ?>"><? echo $this->row->id_label; ?></label>
</li>
