<?
/**
 * Messages Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<div data-alert class="alert-box radius <?= $this->row->class; ?>">
    <?= $this->row->message; ?>
    <a class="close" href="<?= $this->row->action; ?>#">&times;</a>
    <h4 class="alert-heading"><?= $this->row->heading; ?></h4>
</div>
