<?
/**
 * Admindashboard Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
?>
<include formbegin form_name=dashboard/>
    <include type=ui name=navigationtab page_array=<? echo $row->page_array; ?>/>
    <include formend/>

    <section class="dashboard">
        <div class="sortable">
            <br/><br/><br/><br/>

            <h1>This will be the very last thing. It will pull from the section content.</h1>
            <? //echo $this->registry->get('Plugindata', 'PortletOptions'); ?>
        </div>
    </section>
