<?
/**
 * Feed Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
?>
<p>
    <a href="<? echo $row->link; ?>">
        <strong>
            <? echo $row->title; ?>
        </strong>
    </a>
    <? if ($runtime_data->display_snippet == 1) {
        echo '<br />' . $row->description;
    }
    if ($runtime_data->display_published_date == 1) {
        echo '<br />' . '<strong>' . $this->language_controller->translate(
                'Published'
            ) . ':</strong> ' . $row->published_date;
    } ?>
</p>
