<?
/**
 * Form Input Textarea Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
$class = '';
if ($this->row->name === 'content_text') {
    $class = 'class="ckeditor" ';
}
?>
<span data-tooltip class="has-tip" title="{T <?= $this->row->name; ?> T}">
    <label for="<?= $this->row->name; ?>">
        {T <?= $this->row->name; ?> T}
    </label>
</span>
<textarea <?= $class; ?>name="<?= $this->row->name; ?>" rows="10" cols="50"><?= trim($this->row->value); ?></textarea>
