<?
/**
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<section class="hide-for-small" id="toolbar" class="contain-to-grid">
    <div class="row">
        <div class="custom dropdown">
            <form class="custom">
                <!-- Custom Radio -->
                <div class="row">
                    <div class="three columns">
                        <label for="radio1"><input name="radio1" type="radio" id="radio1" style="display:none;"><span
                                class="custom radio"></span> Radio Button 1</label>

                        <label for="radio2"><input name="radio1" type="radio" id="radio2" style="display:none;"><span
                                class="custom radio checked"></span> Radio Button 2</label>
                    </div>
                    <div class="three columns">
                        <label for="checkbox1"><input type="checkbox" id="checkbox1" style="display: none;"><span
                                class="custom checkbox"></span> Label for Checkbox</label>
                        <label for="checkbox2"><input type="checkbox" id="checkbox2" checked
                                                      style="display: none;"><span
                                class="custom checkbox checked"></span> Label for Checkbox</label>
                        <label for="checkbox3"><input type="checkbox" CHECKED id="checkbox3"> Label for Checkbox</label>
                    </div>

                    <!-- Custom Checkbox -->
                    <div class="six columns">
                    </div>
            </form>
        </div>
</section>
