<?
/**
 * Formtextarea Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

$tooltip_css_class = 'has-tip';
?>
    <span class="<? echo $tooltip_css_class; ?>" title="<? echo $this->row->tooltip; ?>"><label
            for="<? echo $this->row->id; ?>"><? echo $this->row->label; ?></label></span><textarea <?
if ($this->row->placeholder == '') {
} else {
    echo 'placeholder' . '="' . $this->row->placeholder . '" ';
}
