<?
/**
 * Formselectlist Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<label><? echo $this->language_controller->translate('SELECT_' . strtoupper($this->row->list_name)); ?></label>
    <select<? echo $this->row->multiple; ?><? echo $this->row->size; ?> name="<? echo $this->row->list_name; ?>" class="inputbox">
    <? if ($this->row->multiple == '') { ?>
            <option value=""><? echo $this->language_controller->translate('SELECT_' . strtoupper($this->row->list_name)); ?></option>
    <? } else {
            $selected = '';
            if ((int) $this->row->no_selection == 1) {
               $selected = ' selected';
            }
    ?>
            <option<? echo $selected; ?> value=""><? echo $this->language_controller->translate('No selection'); ?></option>
    <? }
