<?
/**
 * 404 Template View
 *
 * @package    Molajo\Themes\System
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<div class="row">
    <div class="twelve columns">
        <?= $this->row->content_text; ?>
    </div>
</div>

<div class="row">
    <div class="twelve columns">
        {I Author I}
    </div>
</div>
