<?php
/**
 * @package     Molajo
 * @subpackage  Molajo System Plugin
 * @copyright   Copyright (C) 2011 Amy Stephen. All rights reserved.
 * @license     GNU General Public License Version 2, or later http://www.gnu.org/licenses/gpl.html
 */
defined('MOLAJO') or die;

class MolajoSystemMeta {

    /**
     * Driver
     *
     * Method called by plgMolajoSystem::MolajoOnAfterRender to change the Generated By Label
     *
     * @param	none
     * @return	boolean
     * @since	1.6
     */
    function driver ()
    {
        /** system plugin **/
        $molajoSystemPlugin =& JPluginHelper::getPlugin('system', 'molajo');
        $systemParams = new JParameter($molajoSystemPlugin->params);

        /** Remove Generator Tag **/
        if ($systemParams->def('remove_generator_tag', 0) == 0) {
            return false;
        }
 
//        $string = '<meta name="generator" content="Molajo 1.6 - Open Source Content Management" />';
//        $length = strlen($string);
//        $buffer = JResponse::getBody();
//        $buffer = substr($buffer, 0, strripos ($buffer, $string)).substr($buffer, ((strripos ($buffer, $string)) + $length), 99999);
//        JResponse::setBody($buffer);

        $string = '<meta name="generator" content="Molajo Joomla Based Distribution" />';
        $length = strlen($string)+1;
        $buffer = JResponse::getBody();
        $buffer = substr($buffer, 0, strripos ($buffer, $string)).substr($buffer, ((strripos ($buffer, $string)) + $length), 99999);
        JResponse::setBody(trim($buffer));

        return true;
    }
}