<?
/**
 * Video Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

?>
<div class="video-wrapper">
    <div class="video-container">
        <iframe src="<? echo $row->criteria_video; ?>"
                width="<? echo $row->criteria_width; ?>"
                height="<? echo $row->criteria_height; ?>"
                frameborder="0">
        </iframe>
    </div>
</div>
