<?
/**
 * Customfields Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<tr>
    <td class="name"><?= $this->row->label; ?></td>
    <td class="type"><?= $this->row->type; ?></td>
    <td class="required"><? $this->row->required; ?></td>
    <td class="datalist"><?= $this->row->datalist; ?></td>
    <td class="hidden"><?= $this->row->hidden; ?></td>
    <td>
        <a href="#" class="small button alert radius">
            {T Delete T}
        </a>
    </td>
</tr>
