<?
/**
 * Customfields Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
if ($this->row->new_fieldset == '1') :
    if ($this->row->page_first_row == 'first') :
    elseif ((int)$this->row->first_following === 1) : ?>
        </ol>
        </fieldset>
    <?
    else: ?>
        </tbody>
        </table>
        </fieldset>
    <? endif; ?>
    <? if ($this->row->fieldset_title == 'Create') : ?>
    <fieldset class="two-up">
    <legend><?= $this->row->fieldset_title; ?></legend>
    <? if ($this->registry->get('runtime_data', 'application_help') == 1) : ?>
        <p><?= $this->row->fieldset_description; ?></p>
    <? endif; ?>
    <ol>
<? else : ?>
    <fieldset>
    <legend><?= $this->row->fieldset_title; ?></legend>
    <? if ($this->registry->get('runtime_data', 'application_help') == 1) : ?>
        <p><?= $this->row->fieldset_description; ?></p>
    <? endif; ?>
    <table class="responsive">
    <thead>
    <tr>
        <th class="name">{T Name T}</th>
        <th class="type">{T Type T}</th>
        <th class="required">{T Required T}</th>
        <th class="datalist">{T List T}</th>
        <th class="hidden">{T Hidden T}</th>
        <th width="1%">
            {T Delete T}
        </th>
    </tr>
    </thead>
    <tbody>
<? endif;
endif; ?>

<? if ($this->row->tab_fieldset_title == 'Create') : ?>
    <li>
        <?= $this->row->view; ?>
        {I template=<?= $this->row->view; ?> parameter_np=<?= $this->row->name; ?> I}
    </li>

<? else: ?>
    <tr>
        <td class="name">{T <?= $this->row->label; ?> T}</td>
        <td class="type"><?= $this->row->type; ?></td>
        <td class="required"><? $this->row->required; ?></td>
        <td class="datalist"><?= $this->row->datalist; ?></td>
        <td class="hidden"><?= $this->row->hidden; ?></td>
        <td><a href="#" class="small button alert radius">{T Delete T}</a></td>
    </tr>
<? endif;
