<?
/**
 * Application Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

?>
$template   = ucfirst(strtolower($this->row->fieldset_template_view));
$this->runtime_data = $this->row->fieldset_template_view_parameter; ?>
<include <? echo $template; ?> parameter=<? echo $this->runtime_data; ?>/>
