<?
/**
 * Comment Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

if ($this->row->closed == 1) {
    $comment = $this->row->closed_comment;

} elseif ($this->row->count_of_comments == 0) {
    $comment = $this->row->content_text;

} else {
    $comment = $this->row->content_text . ' ' . $this->row->count_of_comments . '.';
} ?>
<div class="comment-head">
    <h3><? echo $this->row->title; ?></h3>

    <p><? echo $comment; ?><p>
</div>
