<?
/**
 * Item Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<h3>
    <?= $this->row->title; ?>
    <small>{T Created by T}
        <a href="#">
            <?= $this->row->created_by_full_name; ?>
        </a>
        {T on T}
        <?=
        $this->row->start_publishing_datetime_day_name
        . ', ' . $this->row->start_publishing_datetime_month_name
        . ' ' . $this->row->start_publishing_datetime_dd
        . ', ' . $this->row->start_publishing_datetime_ccyy;
        ?>.
    </small>
</h3>
<p>
    <?= $this->row->content_text; ?>
</p>

<h4>
    {T Hierarchy T}
</h4>
<ul>
    <li><strong>Department:</strong> <a href="/admin/comments/74">Department A</a></li>
    <li><strong>College:</strong> <a href="/admin/comments/88">College A</a></li>
    <li><strong>VC/VP:</strong> <a href="/admin/comments/73">VC/VP A</a></li>
    <li><strong>Campus:</strong> <a href="/admin/comments/72">Campus A</a></li>
    <li><strong>Institution:</strong> <a href="/admin/comments/71">University of Nebraska</a></li>
</ul>
