<?
/**
 * Article Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
$id    = $this->row->id;
$start = substr($this->row->start_publishing_datetime, 0, 10);

$comment_form_open_days = (int)$this->parameters->enable_response_comment_form_open_days;
$comments               = (int)$this->parameters->enable_response_comments;

$author_profile = 1;
?>
<h3>
    <?= $this->row->title; ?>
</h3>

<h4>
    <small>
        {T Written by T}
        <a href="#">
            <?= $this->row->created_by_full_name; ?>
        </a>
        {T on T}
        <?=
        $this->row->start_publishing_datetime_day_name
        . ', ' . $this->row->start_publishing_datetime_month_name
        . ' ' . $this->row->start_publishing_datetime_dd
        . ', ' . $this->row->start_publishing_datetime_ccyy;
        ?>
    </small>
</h4>

<?= $this->row->content_text; ?>

<? if ($author_profile === 1) : ?>
    {I Author author=<?= $this->row->created_by; ?> wrap=Nav wrap_class=author-profile I}
<? endif; ?>

<? if ($comments === 1) : ?>
    {I Comments source_id=<?= $id; ?> start_publish=<?= $start; ?> comment_form_open_days=<?= $comment_form_open_days; ?> I}
<? endif;
