<?
/**
 * Article Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>

<h4>
    Hierarchy
</h4>
<ul>
    <li><strong>Institution:</strong> <a href="/admin/comments/71">University of Nebraska</a></li>
</ul>


<h4>
    VC/VP
</h4>
<ul>
    <li><a href="/admin/comments/73">VC/VP A</a></li>
    <li><a href="/admin/comments/73">VC/VP B</a></li>
    <li><a href="/admin/comments/73">VC/VP C</a></li>
</ul>
