<?
/**
 * Article Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<h4>
    Hierarchy
</h4>
<ul>
    <li><strong>VC/VP:</strong> <a href="/admin/comments/73">VC/VP A</a></li>
    <li><strong>Campus:</strong> <a href="/admin/comments/72">Campus A</a></li>
    <li><strong>Institution:</strong> <a href="/admin/comments/71">University of Nebraska</a></li>
</ul>


<h4>
    Departments
</h4>
<ul>
    <li><a href="/admin/comments/74">Department A College A</a></li>
    <li><a href="/admin/comments/75">Department B College A</a></li>
    <li><a href="/admin/comments/80">Department C College A</a></li>
</ul>
