<?
/**
 * Article Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<h4>
    Hierarchy
</h4>
<ul>
    <li><strong>College:</strong> <a href="/admin/comments/88">College A</a></li>
    <li><strong>VC/VP:</strong> <a href="/admin/comments/73">VC/VP A</a></li>
    <li><strong>Campus:</strong> <a href="/admin/comments/72">Campus A</a></li>
    <li><strong>Institution:</strong> <a href="/admin/comments/71">University of Nebraska</a></li>
</ul>


<h4>
    Financials
</h4>
<ul>
    <li><strong>91-4401-0100</strong> <a href="/admin/articles/article-12">CSN Director Activities (91-4401-0100) </a>
    </li>
    <li><strong>91-4435-99999</strong> <a href="/admin/articles/article-5">QVX Blue (91-4450-0200) </a></li>
</ul>


<h4>
    Human Resources
</h4>
<ul>
    <li><strong>111111</strong> <a href="/admin/pages/about-us">HR Code 1 (111111) </a></li>
</ul>

<h4>
    Student System
</h4>
<ul>
    <li><strong>11-111</strong> <a href="/admin/contacts/contact-1">SIS Code 1 (11-111)</a></li>
</ul>
