<?
/**
 * Article Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>

<h4>
    Hierarchy
</h4>
<ul>
    <li><a href="/admin/comments/72">Campus A</a></li>
    <li><a href="/admin/comments/72">Campus B</a></li>
    <li><a href="/admin/comments/72">Campus C</a></li>
    <li><a href="/admin/comments/72">Campus D</a></li>
</ul>
