<?
/**
 * Article Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>

<h4>
    Hierarchy
</h4>
<ul>
    <li><strong>Campus:</strong> <a href="/admin/comments/72">Campus A</a></li>
    <li><strong>Institution:</strong> <a href="/admin/comments/71">University of Nebraska</a></li>
</ul>


<h4>
    Colleges
</h4>
<ul>
    <li><a href="/admin/comments/88">College A</a></li>
    <li><a href="/admin/comments/89">College B</a></li>
    <li><a href="/admin/comments/90">College C</a></li>
</ul>
