<?
/**
 * Article Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
    <h3>
        <?= $this->row->title; ?>
    </h3>
    <p>
        <small>{T Last Updated by T}
            <a href="#">
                <?= $this->row->created_by_full_name; ?>
            </a>
            {T on T}
            <?=
            $this->row->start_publishing_datetime_day_name
            . ', ' . $this->row->start_publishing_datetime_month_name
            . ' ' . $this->row->start_publishing_datetime_dd
            . ', ' . $this->row->start_publishing_datetime_ccyy;
            ?>.
        </small>
    </p>
    <p><?= $this->row->content_text; ?></p>
<?
if ((int)$this->row->lvl == 1) {
    include __DIR__ . '/University.phtml';
} elseif ((int)$this->row->lvl == 2) {
    include __DIR__ . '/Campus.phtml';
} elseif ((int)$this->row->lvl == 3) {
    include __DIR__ . '/Vcvp.phtml';
} elseif ((int)$this->row->lvl == 4) {
    include __DIR__ . '/College.phtml';
} else {
    include __DIR__ . '/Department.phtml';
}
