<?
/**
 * Formbegin Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
$extra = '';
if ($this->row->form_method === ' method="PUT"') {
    $extra = '<input type="hidden" name="_method" value="PUT" />' . chr(10);
    $this->row->form_method = ' method="POST"';
} elseif ($this->row->form_method === ' method="DELETE"') {
    $extra = '<input type="hidden" name="_method" value="DELETE" />' . chr(10);
    $this->row->form_method = ' method="POST"';
}
?>
<form <?=$this->row->form_id . $this->row->form_method . $this->row->form_name . $this->row->form_action . $this->row->form_class . $this->row->form_attributes . '>' . chr(10); ?>
<?= $extra; ?>
