<?
/**
 * Admindashboardtab Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
if ($this->row->new_fieldset == '1') : ?>
</ol>
</fieldset>
<fieldset class="two-up">
    <legend><?= $this->row->tab_fieldset_title; ?></legend>
    <p><?= $this->row->tab_fieldset_description; ?></p>
    <ol>
        <? endif; ?>
        <li>
            {I template=<?= $this->row->view; ?> parameter_np=<?= $this->row->name; ?> I}
        </li>
