<?
/**
 * Gridtags Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
<div id="toolbar-tags" class="row">
    <div class="large-12 columns">
        <div class="row">
            <div class="large-12 columns">
                <h3>{T Tags T}</h3>
            </div>
        </div>
        <div class="row">
            <div class="large-6 small-12 columns">
                {I template=Form_selectlist model_name=grid_batch_tags I}
            </div>
            <div class="large-6 small-12 columns"></div>
        </div>
        <div class="row">
            <div class="large-3 small-6 columns text-right">
                <input type="submit" class="submit button small radius" name="submit" id="AssignTags"
                       value="{T Assign T}"/>
            </div>
            <div class="large-3 small-6 columns right-text">
                <input type="submit" class="submit button small radius" name="submit" id="RemoveTags"
                       value="{T Remove T}"/>
            </div>
            <div class="large-6 small-12 columns"></div>
        </div>
    </div>
</div>
