<?
/**
 * Metadata Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
$application_html5 = $this->row->application_html5;
$end               = $this->row->end;
if (trim($this->row->content) == '') :
elseif ($this->row->name == 'mimetype' && (int)$this->row->application_html5 === 1) :
else : ?>
    <meta <?= $this->row->label; ?>="<?= $this->row->name; ?>" content="<?= $this->row->content; ?>"<?= $end;
endif;
