<?
/**
 * Admindashboardtab Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */


if ($this->row->new_fieldset == '1') {
?>
</ol>
</fieldset>
<fieldset class="two-up">
    <legend><? echo $this->row->tab_fieldset_title; ?></legend>
    <p><? echo $this->row->tab_fieldset_description; ?></p>
    <ol>
        <? } ?>
        <li>
            <include <? echo $this->row->view; ?> parameter_np=<? echo $this->row->name; ?>/>
        </li>
