<?
/**
 * Admindashboardtab Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */


$this->row->new_fieldset = '0';
?>
<h2>
    <span>
        <em><? echo 'Articles Configuration'; ?></em>
        <strong><? echo $this->row->tab_title; ?></strong>
    </span>
</h2>
<p class="tab-description"><? echo $this->row->tab_description; ?></p>
<fieldset class="two-up">
    <legend><? echo $this->row->tab_fieldset_title; ?></legend>
    <p class="fieldset-description"><? echo $this->row->tab_fieldset_description; ?></p>
    <ol>
