<?
/**
 * Assetscss Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */

$application_html5 = $this->row->application_html5;
$end = $this->row->end;

if ($this->row->conditional == '' || $this->row->conditional === null) {
    $begin_conditional = '';
    $end_conditional   = '';
} else {
    if ((int)$application_html5 == 1) {
        $end = '>';
    } else {
        $end = '/>';
    }
    $begin_conditional = '<!--[' . $this->row->conditional . ' ]>';
    $end_conditional   = '<![endif]-->' . chr(10);
}
?>
<? echo $begin_conditional; ?>
    <link rel="stylesheet"
    href="<? echo $this->row->url; ?>"<? if ((int)$this->row->application_html5 == 0): ?>
    type="<? echo $this->row->mimetype; ?>"<? endif; ?><? if ($this->row->media != null): ?>
    media="<? echo $this->row->media; ?>"<? endif; ?><? if (trim(
        $this->row->attributes
    ) != ''
): ?><? echo $this->row->attributes; ?><? endif; ?><? echo $end; ?><? echo $end_conditional;
