<?
/**
 * @package    Molajo
 * @copyright  2013 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<h5 class="subheader">
    <? echo $this->row->title; ?>
</h5>
<p><? //echo $this->row->content_text_snippet; ?></p>
<p><? echo $this->row->content_text; ?></p>
<a class="button" href="<? echo $this->row->catalog_sef_request; ?>">Push it.<br/> You know you want to to.</a>
