<?
/**
 * Customfields Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
if ($row->new_fieldset == '1') {
    if ($row->page_first_row == 'first') {
    } elseif ((int)$row->first_following === 1) {
        ?>
        </ol>
        </fieldset>
    <? } else { ?>
        </tbody>
        </table>
        </fieldset>
    <? } ?>
    <? if ($row->fieldset_title == 'Create') { ?>
        <fieldset class="two-up">
        <legend><? echo $row->fieldset_title; ?></legend>
        <? if ($this->registry->get('runtime_data', 'application_help') == 1) { ?>
            <p><? echo $row->fieldset_description; ?></p>
        <? } ?>
        <ol>
    <? } else { ?>
        <fieldset>
        <legend><? echo $row->fieldset_title; ?></legend>
        <? if ($this->registry->get('runtime_data', 'application_help') == 1) { ?>
            <p><? echo $row->fieldset_description; ?></p>
        <? } ?>
        <table class="responsive">
        <thead>
        <tr>
            <th class="name"><? echo $this->language_controller->translate('Name'); ?></th>
            <th class="type"><? echo $this->language_controller->translate('Type'); ?></th>
            <th class="required"><? echo $this->language_controller->translate('Required'); ?></th>
            <th class="datalist"><? echo $this->language_controller->translate('List'); ?></th>
            <th class="hidden"><? echo $this->language_controller->translate('Hidden'); ?></th>
            <th width="1%">
                <? echo $this->language_controller->translate('Delete'); ?>
            </th>
        </tr>
        </thead>
        <tbody>
    <?
    }
} ?>

<? if ($row->tab_fieldset_title == 'Create') { ?>
    <li>
        <? echo $row->view;
        die;
        ?>
        <include <? echo $row->view; ?> parameter_np=<? echo $row->name; ?>/>
    </li>

<? } else { ?>
    <tr>
        <td class="name"><? echo $this->language_controller->translate($row->label); ?></td>
        <td class="type"><? echo $row->type; ?></td>
        <td class="required"><? $row->required; ?></td>
        <td class="datalist"><? echo $row->datalist; ?></td>
        <td class="hidden"><? echo $row->hidden; ?></td>
        <td><a href="#" class="small button alert radius"><? echo $this->language_controller->translate(
                    'Delete',
                    'Delete'
                ); ?></a></td>
    </tr>
<?
}
