<?
/**
 * Formpage Template View
 *
 * @package    Molajo\Themes\Foundation5
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 */
?>
    <header class="configuration-header">
        <header class="configuration-header-header">
            <h3><?= $this->row->page_title_extended; ?></h3>
            <? if ($this->runtime_data->application_help == 1) : ?>
                <h6><?= $this->row->page_description; ?></h6>
            <? endif; ?>
        </header>
        <section class="configuration-header-section">
            <ul class="inline-list right">
                <li><a href="#"><strong>{T Reset/></strong></a></li>
                <li>
                    <a href="#" class="button success radius">
                        {T Save T}
                    </a>
                </li>
            </ul>
        </section>
    </header>
<? if ($this->row->page_subtitle_first_row == 1) :
else : ?>
    <div class="configuration-body">
<? endif;
