<?
/**
 * Sidebar Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
?>

<h3>Categories</h3>
<ul class="side-nav">
    <li><a href="#">News</a></li>
    <li><a href="#">Code</a></li>
    <li><a href="#">Design</a></li>
    <li><a href="#">Fun</a></li>
    <li><a href="#">Weasels</a></li>
</ul>
<include Featured wrap=Div wrap_class=panel/>
