<?
/**
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
$copyright_statement = '© 2014-2015 Molajo';
?>
<div class="row">
    <div class="small-12 medium-12 large-12 columns">
        <ul class="footer-links">
            <li><a href="#top">&uarr;
                    {T Back to Top T}
                </a>
            </li>
            <li><a href="/pages/about-us">
                    {T About Us T}
                </a>
            </li>
            <li><a href="/pages/contact-us">
                    {T Contact Us T}
                </a>
            </li>
            <li><a href="/pages/privacy-policy">
                    {T Privacy Policy T}
                </a>
            </li>
            <li><a href="/pages/site-map">
                    {T Site Map T}
                </a>
            </li>
        </ul>
        <p class="copyright">
            <?= $copyright_statement; ?>
        </p>
    </div>
</div>
