<?
/**
 * @package    Molajo\Themes\Foundation5
 * @copyright  2014-2015 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
$base_url = $this->runtime_data->application->base_url;
$page_url = $this->runtime_data->request->data->url;
$home_url = $this->runtime_data->application->base_url;

$thru_now = '';

$copyright_statement = '&copy; '
    . ' ' . $this->language_controller->translate('Copyright')
    . ' ' . $this->parameters->copyright_first_year
    . $thru_now;
?>
<footer class="footer-bottom" role="contentinfo">
    <div class="row">
        <div class="small-12 medium-12 large-12 columns">
            <ul class="footer-links">
                <li><a href="<?= $page_url; ?>#top">&uarr;
                        {T Back to Top T}
                    </a>
                </li>
                <li><a href="<?= $base_url; ?>pages/about-us">
                        {T About Us T}
                    </a>
                </li>
                <li><a href="<?= $base_url; ?>pages/contact-us">
                        {T Contact Us T}
                    </a>
                </li>
                <li><a href="<?= $base_url; ?>pages/privacy-policy">
                        {T Privacy Policy T}
                    </a>
                </li>
                <li><a href="<?= $base_url; ?>pages/site-map">
                        {T Site Map T}
                    </a>
                </li>
            </ul>
            <p class="copyright">
                <?= $copyright_statement; ?>
                <a href="<?= $this->parameters->link; ?>">
                    <?= $this->parameters->linked_text; ?>
                </a>
                <?= $this->parameters->copyright_holder; ?>
            </p>
        </div>
    </div>
</footer>
