<?
/**
 * Gridsticky Template View
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 */
$action = $this->runtime_data->page->urls['page'];
if ($this->row->enable == 1) {
    ?>
    <div class="grid-sticky grid-batch">
        <ol class="grid-batch">
            <li><strong><? echo $this->language_controller->translate('Sticky Assignment'); ?></strong></li>
            <li><input type="submit" class="submit button small radius" name="submit" id="Sticky" value="Sticky"></li>
            <li><input type="submit" class="submit button small radius" name="submit" id="Unsticky" value="Unsticky">
            </li>
        </ol>
    </div>
<?
}
